-- ModeMorph Database Schema
-- Exported from Supabase on 2026-04-10T12:43:27.865318
-- Auto-generated by export_supabase.py

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Table: basic_item_materials
CREATE TABLE IF NOT EXISTS "basic_item_materials" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "basic_item_id" INTEGER,
    "basic_material_id" INTEGER,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("basic_item_id", "basic_material_id")
);



-- Table: basic_materials
CREATE TABLE IF NOT EXISTS "basic_materials" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name_ru" TEXT NOT NULL,
    "description" TEXT,
    "properties" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    "image_url" TEXT,
    "name_en" TEXT,
    PRIMARY KEY ("id")
);

-- Table: basic_wardrobe_items
CREATE TABLE IF NOT EXISTS "basic_wardrobe_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name_ru" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    "image_url" TEXT,
    "name_en" TEXT,
    "clothing_type" VARCHAR(50) DEFAULT 'верхняя',
    "gender" TEXT,
    "temp_min" INTEGER,
    "temp_max" INTEGER,
    PRIMARY KEY ("id")
);

-- Table: broadcast_messages
CREATE TABLE IF NOT EXISTS "broadcast_messages" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "admin_user_id" UUID NOT NULL,
    "message_text" TEXT NOT NULL,
    "recipient_filter" JSONB DEFAULT '{"type": "all"}'::jsonb,
    "total_sent" INTEGER DEFAULT 0,
    "total_failed" INTEGER DEFAULT 0,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: combination_elements
CREATE TABLE IF NOT EXISTS "combination_elements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "combination_id" BIGINT NOT NULL,
    "basic_item_id" BIGINT,
    "basic_material_id" BIGINT,
    "position" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);




-- Table: combinations
CREATE TABLE IF NOT EXISTS "combinations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "combination_type" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: credit_packs
CREATE TABLE IF NOT EXISTS "credit_packs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "credits" INTEGER NOT NULL,
    "price_rub" INTEGER NOT NULL,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: credit_transactions
CREATE TABLE IF NOT EXISTS "credit_transactions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_profile_id" BIGINT NOT NULL,
    "transaction_type" VARCHAR(20) NOT NULL,
    "amount" INTEGER NOT NULL,
    "description" TEXT,
    "feature_used" VARCHAR(50),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "reason" TEXT,
    "metadata" JSONB,
    PRIMARY KEY ("id")
);


-- Table: daily_user_activity
CREATE TABLE IF NOT EXISTS "daily_user_activity" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_profile_id" BIGINT NOT NULL,
    "activity_date" DATE NOT NULL,
    "first_seen_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "last_seen_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "activity_count" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("user_profile_id", "activity_date")
);


-- Table: feature_costs
CREATE TABLE IF NOT EXISTS "feature_costs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "feature_name" VARCHAR(50) NOT NULL,
    "display_name" VARCHAR(100) NOT NULL,
    "cost_credits" INTEGER NOT NULL DEFAULT 0,
    "cost_subscription_credits" INTEGER NOT NULL DEFAULT 0,
    "usage_increment" INTEGER NOT NULL DEFAULT 1,
    "description" TEXT,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("feature_name")
);

-- Table: limits
CREATE TABLE IF NOT EXISTS "limits" (
    "user_profile_id" BIGINT NOT NULL,
    "wardrobe_items_anlyzed" INTEGER NOT NULL DEFAULT 0,
    "ai_requests" INTEGER NOT NULL DEFAULT 0,
    "ideas_viewed" INTEGER NOT NULL DEFAULT 0,
    "outfits_saved" INTEGER NOT NULL DEFAULT 0,
    "vton_used" INTEGER NOT NULL DEFAULT 0,
    "wardrobe_items_anlyzed_updated_at" TIMESTAMPTZ,
    "ai_requests_updated_at" TIMESTAMPTZ,
    "ideas_viewed_updated_at" TIMESTAMPTZ,
    "outfits_saved_updated_at" TIMESTAMPTZ,
    "vton_used_updated_at" TIMESTAMPTZ,
    "ai_last_reset_at" TIMESTAMPTZ,
    "monthly_cycle_started_at" TIMESTAMPTZ,
    "ideas_outfits_last_reset_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("user_profile_id")
);


-- Table: looks_sections
CREATE TABLE IF NOT EXISTS "looks_sections" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: main_recommendations
CREATE TABLE IF NOT EXISTS "main_recommendations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID NOT NULL,
    "run_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "look_sections" JSONB NOT NULL,
    "source" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: outfit_items
CREATE TABLE IF NOT EXISTS "outfit_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "outfit_id" BIGINT NOT NULL,
    "wardrobe_item_id" BIGINT NOT NULL,
    "position" INTEGER DEFAULT 0,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("outfit_id", "wardrobe_item_id")
);



-- Table: outfits
CREATE TABLE IF NOT EXISTS "outfits" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "user_id" UUID NOT NULL,
    "season" TEXT,
    "occasion" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    "likes" INTEGER DEFAULT 0,
    "preview_image_url" TEXT,
    "favorites_count" INTEGER DEFAULT 0,
    "views_count" INTEGER DEFAULT 0,
    "gender" TEXT,
    PRIMARY KEY ("id")
);

-- Table: payments
CREATE TABLE IF NOT EXISTS "payments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "invoice_id" BIGINT NOT NULL,
    "provider" TEXT NOT NULL DEFAULT 'robokassa',
    "amount" NUMERIC(12,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'RUB',
    "status" TEXT NOT NULL DEFAULT 'pending',
    "description" TEXT,
    "meta" JSONB DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: recs_jobs
CREATE TABLE IF NOT EXISTS "recs_jobs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID NOT NULL,
    "run_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "status" TEXT NOT NULL,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: recs_settings
CREATE TABLE IF NOT EXISTS "recs_settings" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    PRIMARY KEY ("key")
);

-- Table: reminder_configs
CREATE TABLE IF NOT EXISTS "reminder_configs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "message_template" TEXT NOT NULL,
    "reminder_type" TEXT NOT NULL DEFAULT 'daily',
    "day_of_week" INTEGER,
    "conditions" JSONB DEFAULT '{}'::jsonb,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: section_looks
CREATE TABLE IF NOT EXISTS "section_looks" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "section_id" INTEGER NOT NULL,
    "look_id" INTEGER NOT NULL,
    "added_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("section_id", "look_id")
);



-- Table: subscription_pricing
CREATE TABLE IF NOT EXISTS "subscription_pricing" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "plan_type" TEXT NOT NULL,
    "price_rub" INTEGER NOT NULL,
    "credits" INTEGER NOT NULL,
    "display_name" TEXT NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("plan_type")
);

-- Table: usage_events
CREATE TABLE IF NOT EXISTS "usage_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "user_profile_id" BIGINT,
    "user_anon_id" TEXT NOT NULL,
    "feature" VARCHAR(64) NOT NULL,
    "action" VARCHAR(64) NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 1,
    "is_subscriber" BOOLEAN NOT NULL,
    "has_bought_credits" BOOLEAN NOT NULL,
    "credits_balance" INTEGER,
    "limits_snapshot" JSONB,
    "page_path" TEXT,
    "item_id" BIGINT,
    "request_id" UUID,
    "metadata" JSONB,
    PRIMARY KEY ("id")
);


-- Table: user_avatars
CREATE TABLE IF NOT EXISTS "user_avatars" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "url" TEXT NOT NULL,
    "is_primary" BOOLEAN DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    PRIMARY KEY ("id")
);

-- Table: user_credits
CREATE TABLE IF NOT EXISTS "user_credits" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_profile_id" BIGINT NOT NULL,
    "credits_balance" INTEGER NOT NULL DEFAULT 0,
    "total_earned" INTEGER NOT NULL DEFAULT 0,
    "total_spent" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);


-- Table: user_events
CREATE TABLE IF NOT EXISTS "user_events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_profile_id" BIGINT NOT NULL,
    "event_type" VARCHAR(100) NOT NULL,
    "event_data" JSONB,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);


-- Table: user_fittings
CREATE TABLE IF NOT EXISTS "user_fittings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "avatar_id" UUID NOT NULL,
    "outfit_items" JSONB NOT NULL,
    "result_image_url" TEXT,
    "status" TEXT DEFAULT 'pending',
    "error_message" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: user_likes
CREATE TABLE IF NOT EXISTS "user_likes" (
    "id" BIGINT NOT NULL,
    "user_id" UUID NOT NULL,
    "outfit_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("user_id", "outfit_id")
);


-- Table: user_looks
CREATE TABLE IF NOT EXISTS "user_looks" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "items" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "image_url" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("id")
);

-- Table: user_profiles
CREATE TABLE IF NOT EXISTS "user_profiles" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID,
    "is_admin" BOOLEAN DEFAULT false,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    "height" INTEGER,
    "weight" NUMERIC(5,2),
    "top_size" VARCHAR(10),
    "bottom_size" VARCHAR(10),
    "shoe_size" VARCHAR(10),
    "gender" VARCHAR(20),
    "full_name" TEXT,
    "avatar_url" TEXT,
    "referral" TEXT,
    "onboarding_complete" BOOLEAN DEFAULT true,
    "notifications_enabled" BOOLEAN DEFAULT true,
    PRIMARY KEY ("id"),
    UNIQUE ("user_id")
);

-- Table: user_style_profiles
CREATE TABLE IF NOT EXISTS "user_style_profiles" (
    "user_id" UUID NOT NULL,
    "mean_vector" TEXT[],
    "clusters" JSONB,
    "total_items" INTEGER,
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY ("user_id")
);

-- Table: user_subscriptions
CREATE TABLE IF NOT EXISTS "user_subscriptions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_profile_id" BIGINT NOT NULL,
    "subscription_type" VARCHAR(20) NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'active',
    "credits_included" INTEGER NOT NULL DEFAULT 40,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "expires_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "start_date" TIMESTAMPTZ DEFAULT now(),
    "end_date" TIMESTAMPTZ,
    PRIMARY KEY ("id")
);


-- Table: wardrobe_items
CREATE TABLE IF NOT EXISTS "wardrobe_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "item_name" TEXT NOT NULL,
    "size_type" TEXT,
    "material" TEXT,
    "style" TEXT,
    "has_print" BOOLEAN DEFAULT false,
    "color" TEXT,
    "shade" TEXT,
    "has_details" BOOLEAN DEFAULT false,
    "url" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    "is_basic" BOOLEAN DEFAULT false,
    "basic_item_id" BIGINT,
    "notes" TEXT,
    "basic_material_id" BIGINT,
    "is_hidden" BOOLEAN DEFAULT false,
    "image_url" TEXT,
    "clothing_type" VARCHAR(50) DEFAULT 'верхняя',
    "item_name_en" TEXT,
    "description" TEXT,
    "description_en" TEXT,
    "gender" TEXT,
    "temp_min" INTEGER,
    "temp_max" INTEGER,
    "embedding" TEXT[],
    PRIMARY KEY ("id")
);




-- Table: wardrobe_user_items
CREATE TABLE IF NOT EXISTS "wardrobe_user_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "user_id" UUID NOT NULL,
    "item_name" TEXT,
    "size_type" TEXT,
    "material" TEXT,
    "style" TEXT,
    "has_print" BOOLEAN DEFAULT false,
    "color" TEXT,
    "shade" TEXT,
    "has_details" BOOLEAN DEFAULT false,
    "url" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    "is_basic" BOOLEAN DEFAULT false,
    "basic_item_id" BIGINT,
    "notes" TEXT,
    "basic_material_id" BIGINT,
    "is_hidden" BOOLEAN DEFAULT false,
    "image_url" TEXT,
    "shop_url" TEXT,
    "clothing_type" VARCHAR(50) DEFAULT 'верхняя',
    "item_name_en" TEXT,
    "description" TEXT,
    "description_en" TEXT,
    "temp_min" INTEGER,
    "temp_max" INTEGER,
    "embedding" TEXT[],
    PRIMARY KEY ("id")
);

-- Table: weather_cache
CREATE TABLE IF NOT EXISTS "weather_cache" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "city_name" VARCHAR(255) NOT NULL,
    "latitude" NUMERIC(10,8) NOT NULL,
    "longitude" NUMERIC(11,8) NOT NULL,
    "temperature" INTEGER NOT NULL,
    "condition" VARCHAR(50) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "humidity" INTEGER NOT NULL,
    "wind_speed" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now(),
    "user_id" UUID,
    PRIMARY KEY ("id")
);


-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS basic_item_materials_basic_item_id_basic_material_id_key ON public.basic_item_materials USING btree (basic_item_id, basic_material_id);
CREATE INDEX IF NOT EXISTS idx_basic_item_materials_item_id ON public.basic_item_materials USING btree (basic_item_id);
CREATE INDEX IF NOT EXISTS idx_basic_item_materials_material_id ON public.basic_item_materials USING btree (basic_material_id);
CREATE INDEX IF NOT EXISTS idx_basic_materials_name ON public.basic_materials USING btree (name_ru);
CREATE INDEX IF NOT EXISTS idx_basic_wardrobe_items_clothing_type ON public.basic_wardrobe_items USING btree (clothing_type);
CREATE INDEX IF NOT EXISTS idx_basic_wardrobe_items_name ON public.basic_wardrobe_items USING btree (name_ru);
CREATE INDEX IF NOT EXISTS idx_combination_elements_basic_item_id ON public.combination_elements USING btree (basic_item_id);
CREATE INDEX IF NOT EXISTS idx_combination_elements_basic_material_id ON public.combination_elements USING btree (basic_material_id);
CREATE INDEX IF NOT EXISTS idx_combination_elements_combination_id ON public.combination_elements USING btree (combination_id);
CREATE INDEX IF NOT EXISTS idx_combinations_type ON public.combinations USING btree (combination_type);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_user_profile_id ON public.credit_transactions USING btree (user_profile_id);
CREATE INDEX IF NOT EXISTS idx_credit_tx_reason ON public.credit_transactions USING btree (reason);
CREATE INDEX IF NOT EXISTS idx_daily_user_activity_date ON public.daily_user_activity USING btree (activity_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_user_activity_date_user ON public.daily_user_activity USING btree (activity_date, user_profile_id);
CREATE INDEX IF NOT EXISTS idx_daily_user_activity_user_profile ON public.daily_user_activity USING btree (user_profile_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_user_activity_per_day ON public.daily_user_activity USING btree (user_profile_id, activity_date);
CREATE UNIQUE INDEX IF NOT EXISTS feature_costs_feature_name_key ON public.feature_costs USING btree (feature_name);
CREATE INDEX IF NOT EXISTS idx_limits_user_profile_id ON public.limits USING btree (user_profile_id);
CREATE INDEX IF NOT EXISTS idx_looks_sections_user_id ON public.looks_sections USING btree (user_id);
CREATE INDEX IF NOT EXISTS gin_main_recommendations_look_sections ON public.main_recommendations USING gin (look_sections jsonb_path_ops);
CREATE INDEX IF NOT EXISTS ix_main_recommendations_run_date ON public.main_recommendations USING btree (run_date);
CREATE INDEX IF NOT EXISTS ix_main_recommendations_user ON public.main_recommendations USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_main_recommendations_user_day ON public.main_recommendations USING btree (user_id, run_date);
CREATE INDEX IF NOT EXISTS idx_outfit_items_outfit_id ON public.outfit_items USING btree (outfit_id);
CREATE INDEX IF NOT EXISTS idx_outfit_items_wardrobe_item_id ON public.outfit_items USING btree (wardrobe_item_id);
CREATE UNIQUE INDEX IF NOT EXISTS outfit_items_outfit_id_wardrobe_item_id_key ON public.outfit_items USING btree (outfit_id, wardrobe_item_id);
CREATE INDEX IF NOT EXISTS idx_outfits_created_at ON public.outfits USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_outfits_favorites_count ON public.outfits USING btree (favorites_count);
CREATE INDEX IF NOT EXISTS idx_outfits_likes ON public.outfits USING btree (likes DESC);
CREATE INDEX IF NOT EXISTS idx_outfits_preview_image ON public.outfits USING btree (preview_image_url) WHERE (preview_image_url IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_outfits_user_id ON public.outfits USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_outfits_views_count ON public.outfits USING btree (views_count);
CREATE INDEX IF NOT EXISTS payments_invoice_id_idx ON public.payments USING btree (invoice_id);
CREATE INDEX IF NOT EXISTS payments_status_idx ON public.payments USING btree (status);
CREATE INDEX IF NOT EXISTS payments_user_id_idx ON public.payments USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_recs_jobs_status_day ON public.recs_jobs USING btree (status, run_date);
CREATE UNIQUE INDEX IF NOT EXISTS ux_recs_jobs_user_day ON public.recs_jobs USING btree (user_id, run_date);
CREATE INDEX IF NOT EXISTS idx_section_looks_look_id ON public.section_looks USING btree (look_id);
CREATE INDEX IF NOT EXISTS idx_section_looks_section_id ON public.section_looks USING btree (section_id);
CREATE UNIQUE INDEX IF NOT EXISTS section_looks_section_id_look_id_key ON public.section_looks USING btree (section_id, look_id);
CREATE UNIQUE INDEX IF NOT EXISTS subscription_pricing_plan_type_key ON public.subscription_pricing USING btree (plan_type);
CREATE INDEX IF NOT EXISTS idx_usage_events_feature ON public.usage_events USING btree (feature, action);
CREATE INDEX IF NOT EXISTS idx_usage_events_profile_time ON public.usage_events USING btree (user_profile_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_usage_events_sub ON public.usage_events USING btree (is_subscriber, has_bought_credits);
CREATE INDEX IF NOT EXISTS idx_usage_events_when ON public.usage_events USING btree (occurred_at);
CREATE INDEX IF NOT EXISTS idx_user_avatars_is_primary ON public.user_avatars USING btree (user_id, is_primary);
CREATE INDEX IF NOT EXISTS idx_user_avatars_user_id ON public.user_avatars USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_credits_user_profile_id_key ON public.user_credits USING btree (user_profile_id);
CREATE INDEX IF NOT EXISTS idx_user_events_created_at ON public.user_events USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_event_type ON public.user_events USING btree (event_type);
CREATE INDEX IF NOT EXISTS idx_user_events_user_event_created ON public.user_events USING btree (user_profile_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_user_profile_id ON public.user_events USING btree (user_profile_id);
CREATE INDEX IF NOT EXISTS idx_user_fittings_avatar_id ON public.user_fittings USING btree (avatar_id);
CREATE INDEX IF NOT EXISTS idx_user_fittings_created_at ON public.user_fittings USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_fittings_status ON public.user_fittings USING btree (status);
CREATE INDEX IF NOT EXISTS idx_user_fittings_user_id ON public.user_fittings USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_likes_outfit_id ON public.user_likes USING btree (outfit_id);
CREATE INDEX IF NOT EXISTS idx_user_likes_user_id ON public.user_likes USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_likes_user_outfit_unique ON public.user_likes USING btree (user_id, outfit_id);
CREATE INDEX IF NOT EXISTS idx_user_looks_created_at ON public.user_looks USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_looks_user_id ON public.user_looks USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON public.user_profiles USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_profiles_user_id_key ON public.user_profiles USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_profile_id ON public.user_subscriptions USING btree (user_profile_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_subscriptions_user_profile_id_idx ON public.user_subscriptions USING btree (user_profile_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_subscriptions_user_profile_id_key ON public.user_subscriptions USING btree (user_profile_id);
CREATE INDEX IF NOT EXISTS idx_wardrobe_items_basic_item_id ON public.wardrobe_items USING btree (basic_item_id);
CREATE INDEX IF NOT EXISTS idx_wardrobe_items_basic_material_id ON public.wardrobe_items USING btree (basic_material_id);
CREATE INDEX IF NOT EXISTS idx_wardrobe_items_clothing_type ON public.wardrobe_items USING btree (clothing_type);
CREATE INDEX IF NOT EXISTS idx_wardrobe_items_image_url ON public.wardrobe_items USING btree (image_url);
CREATE INDEX IF NOT EXISTS idx_wardrobe_items_is_basic ON public.wardrobe_items USING btree (is_basic);
CREATE INDEX IF NOT EXISTS idx_wardrobe_items_is_hidden ON public.wardrobe_items USING btree (is_hidden);
CREATE INDEX IF NOT EXISTS idx_wardrobe_items_name ON public.wardrobe_items USING btree (item_name);
CREATE INDEX IF NOT EXISTS idx_wardrobe_user_items_clothing_type ON public.wardrobe_user_items USING btree (clothing_type);
CREATE INDEX IF NOT EXISTS idx_wardrobe_user_items_color ON public.wardrobe_user_items USING btree (color);
CREATE INDEX IF NOT EXISTS idx_wardrobe_user_items_created_at ON public.wardrobe_user_items USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_wardrobe_user_items_is_basic ON public.wardrobe_user_items USING btree (is_basic);
CREATE INDEX IF NOT EXISTS idx_wardrobe_user_items_is_hidden ON public.wardrobe_user_items USING btree (is_hidden);
CREATE INDEX IF NOT EXISTS idx_wardrobe_user_items_item_name ON public.wardrobe_user_items USING btree (item_name);
CREATE INDEX IF NOT EXISTS idx_wardrobe_user_items_material ON public.wardrobe_user_items USING btree (material);
CREATE INDEX IF NOT EXISTS idx_wardrobe_user_items_user_id ON public.wardrobe_user_items USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_wui_has_embedding ON public.wardrobe_user_items USING btree (user_id) WHERE (embedding IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_weather_cache_city_updated ON public.weather_cache USING btree (city_name, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_weather_cache_location ON public.weather_cache USING btree (latitude, longitude, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_weather_cache_user_id ON public.weather_cache USING btree (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_weather_cache_user ON public.weather_cache USING btree (user_id);

-- Supabase auth compatibility stubs
-- These replace auth.uid() and auth.jwt() which are Supabase-specific.
-- In our architecture, auth is handled by FastAPI JWT, not by PostgreSQL RLS.
-- These stubs exist only so that exported PL/pgSQL functions can be created without errors.
CREATE SCHEMA IF NOT EXISTS auth;

CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid AS $$
BEGIN
  -- In FastAPI architecture, auth is handled at the application level.
  -- This stub returns NULL; RPC functions using it should be called
  -- from the backend with explicit user IDs instead.
  RETURN NULL;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION auth.jwt() RETURNS jsonb AS $$
BEGIN
  RETURN '{}'::jsonb;
END;
$$ LANGUAGE plpgsql STABLE;

-- Functions (RPC)

CREATE OR REPLACE FUNCTION public.activate_subscription_and_reset_limits(p_user_profile_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM public.assert_own_profile(p_user_profile_id);
  PERFORM public.ensure_limits_row(p_user_profile_id);

  UPDATE public.limits
  SET wardrobe_items_anlyzed = 50,
      wardrobe_items_anlyzed_updated_at = NOW(),
      vton_used = 100,
      vton_used_updated_at = NOW(),
      ai_requests = 20,
      ai_last_reset_at = NOW(),
      ai_requests_updated_at = NOW(),
      monthly_cycle_started_at = NOW(),
      updated_at = NOW()
  WHERE user_profile_id = p_user_profile_id;

  INSERT INTO public.user_credits (user_profile_id, credits_balance, total_earned)
  VALUES (p_user_profile_id, 40, 40)
  ON CONFLICT (user_profile_id) DO UPDATE
  SET credits_balance = public.user_credits.credits_balance + 40,
      total_earned = public.user_credits.total_earned + 40,
      updated_at = NOW();

  INSERT INTO public.credit_transactions(user_profile_id, amount, reason, description)
  VALUES (p_user_profile_id, 40, 'subscription_bonus', '40 credits on subscription activation');
END;
$function$
;

CREATE OR REPLACE FUNCTION public.add_credits(p_user_profile_id integer, p_amount integer, p_reason text, p_description text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- upsert баланса
  INSERT INTO public.user_credits (user_profile_id, credits_balance, total_earned)
  VALUES (p_user_profile_id, p_amount, p_amount)
  ON CONFLICT (user_profile_id) DO UPDATE
    SET credits_balance = public.user_credits.credits_balance + EXCLUDED.credits_balance,
        total_earned    = public.user_credits.total_earned    + EXCLUDED.total_earned,
        updated_at      = NOW();

  -- лог транзакции: ТИП ДОЛЖЕН БЫТЬ 'credit'
  INSERT INTO public.credit_transactions (
    user_profile_id, transaction_type, amount, description, feature_used, created_at
  ) VALUES (
    p_user_profile_id, 'credit', p_amount, p_description, p_reason, NOW()
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.add_user_credits(credits_to_add integer, description text, target_user_id uuid, transaction_type text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_user_profile_id INTEGER;
    v_is_admin BOOLEAN := FALSE;
BEGIN
    -- Проверка прав (кто вызывает — админ)
    SELECT COALESCE(is_admin, FALSE)
      INTO v_is_admin
      FROM public.user_profiles
     WHERE user_id = auth.uid();

    IF NOT v_is_admin THEN
        RAISE EXCEPTION 'Access denied: Only admins can add credits to users';
    END IF;

    -- Получаем числовой profile.id целевого пользователя
    SELECT id
      INTO STRICT v_user_profile_id
      FROM public.user_profiles
     WHERE user_id = target_user_id;

    -- Upsert баланса (основание — уникальный индекс на user_profile_id)
    INSERT INTO public.user_credits AS uc
        (user_profile_id, credits_balance, total_earned, created_at, updated_at)
    VALUES
        (v_user_profile_id, credits_to_add, credits_to_add, NOW(), NOW())
    ON CONFLICT (user_profile_id) DO UPDATE
       SET credits_balance = uc.credits_balance + EXCLUDED.credits_balance,
           total_earned    = uc.total_earned    + EXCLUDED.total_earned,
           updated_at      = NOW();

    -- Лог транзакции (тип приводим к допустимому по CHECK, например 'credit')
    INSERT INTO public.credit_transactions
        (user_profile_id, transaction_type, amount, description, feature_used, created_at)
    VALUES
        (v_user_profile_id, 'credit', credits_to_add, description, 'admin_grant', NOW());

    RETURN TRUE;

EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Failed to add credits: %', SQLERRM;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.assert_own_profile(p_user_profile_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- 1) Разрешаем сервисным ключам
  IF coalesce(auth.jwt() ->> 'role', '') = 'service_role' THEN
    RETURN;
  END IF;

  -- 2) Разрешаем текущим админам (по вашей функции is_current_user_admin)
  IF public.is_current_user_admin() THEN
    RETURN;
  END IF;

  -- 3) Обычная проверка «сам за себя»
  IF NOT EXISTS (
    SELECT 1
    FROM public.user_profiles up
    WHERE up.id = p_user_profile_id
      AND up.user_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'forbidden: profile mismatch';
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.can_use_feature(p_user_profile_id bigint, p_feature character varying, p_count integer DEFAULT 1)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  l public.limits;
  bal INTEGER := 0;
  need_units INTEGER := 0;
  cost_per_unit INTEGER := 0;
  grant_per_unit INTEGER := 1;
BEGIN
  PERFORM public.assert_own_profile(p_user_profile_id);
  PERFORM public.reconcile_limits(p_user_profile_id);

  SELECT * INTO l FROM public.limits WHERE user_profile_id = p_user_profile_id;

  IF p_feature = 'wardrobe_items_anlyzed' THEN
    IF l.wardrobe_items_anlyzed >= p_count THEN RETURN TRUE; END IF;
    need_units := p_count - l.wardrobe_items_anlyzed; cost_per_unit := 5; grant_per_unit := 1;
  ELSIF p_feature = 'ai_requests' THEN
    IF l.ai_requests >= p_count THEN RETURN TRUE; END IF;
    need_units := p_count - l.ai_requests; cost_per_unit := 2; grant_per_unit := 5;
  ELSIF p_feature = 'vton_used' THEN
    IF l.vton_used >= p_count THEN RETURN TRUE; END IF;
    need_units := p_count - l.vton_used; cost_per_unit := 3; grant_per_unit := 1;
  ELSIF p_feature = 'ideas_viewed' THEN
    RETURN l.ideas_viewed >= p_count;
  ELSIF p_feature = 'outfits_saved' THEN
    RETURN l.outfits_saved >= p_count;
  ELSE
    RETURN FALSE;
  END IF;

  SELECT credits_balance INTO bal FROM public.user_credits WHERE user_profile_id = p_user_profile_id;
  IF bal IS NULL THEN bal := 0; END IF;

  RETURN bal >= CEIL(need_units::NUMERIC / grant_per_unit) * cost_per_unit;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_daily_limit(p_user_id uuid, p_usage_type character varying, p_increment integer DEFAULT 1)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
  current_usage INTEGER := 0;
  daily_limit INTEGER := 0;
  has_subscription BOOLEAN := FALSE;
BEGIN
  -- Check if user has active subscription
  SELECT EXISTS(
    SELECT 1 FROM user_subscriptions 
    WHERE user_id = p_user_id 
    AND status = 'active' 
    AND expires_at > NOW()
  ) INTO has_subscription;
  
  -- Get current daily usage
  SELECT 
    CASE 
      WHEN p_usage_type = 'wardrobe_digitizations' THEN COALESCE(wardrobe_digitizations, 0)
      WHEN p_usage_type = 'ai_requests' THEN COALESCE(ai_requests, 0)
      WHEN p_usage_type = 'ideas_views' THEN COALESCE(ideas_views, 0)
      WHEN p_usage_type = 'outfits_saved' THEN COALESCE(outfits_saved, 0)
      ELSE 0
    END
  INTO current_usage
  FROM daily_usage 
  WHERE user_id = p_user_id AND usage_date = CURRENT_DATE;
  
  -- Set limits based on subscription status
  CASE p_usage_type
    WHEN 'wardrobe_digitizations' THEN daily_limit := 5;
    WHEN 'ai_requests' THEN daily_limit := CASE WHEN has_subscription THEN 20 ELSE 1 END;
    WHEN 'ideas_views' THEN daily_limit := 10;
    WHEN 'outfits_saved' THEN daily_limit := 999; -- No daily limit, only total limit
    ELSE daily_limit := 0;
  END CASE;
  
  -- Check if limit would be exceeded
  IF current_usage + p_increment > daily_limit THEN
    RETURN FALSE;
  END IF;
  
  -- Update usage
  INSERT INTO daily_usage (user_id, usage_date, wardrobe_digitizations, ai_requests, ideas_views, outfits_saved)
  VALUES (
    p_user_id, 
    CURRENT_DATE,
    CASE WHEN p_usage_type = 'wardrobe_digitizations' THEN p_increment ELSE 0 END,
    CASE WHEN p_usage_type = 'ai_requests' THEN p_increment ELSE 0 END,
    CASE WHEN p_usage_type = 'ideas_views' THEN p_increment ELSE 0 END,
    CASE WHEN p_usage_type = 'outfits_saved' THEN p_increment ELSE 0 END
  )
  ON CONFLICT (user_id, usage_date) DO UPDATE SET
    wardrobe_digitizations = daily_usage.wardrobe_digitizations + 
      CASE WHEN p_usage_type = 'wardrobe_digitizations' THEN p_increment ELSE 0 END,
    ai_requests = daily_usage.ai_requests + 
      CASE WHEN p_usage_type = 'ai_requests' THEN p_increment ELSE 0 END,
    ideas_views = daily_usage.ideas_views + 
      CASE WHEN p_usage_type = 'ideas_views' THEN p_increment ELSE 0 END,
    outfits_saved = daily_usage.outfits_saved + 
      CASE WHEN p_usage_type = 'outfits_saved' THEN p_increment ELSE 0 END,
    updated_at = NOW();
    
  RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_total_limit(p_user_id uuid, p_limit_type character varying)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
  current_count INTEGER := 0;
  total_limit INTEGER := 0;
BEGIN
  -- Get current totals
  SELECT 
    CASE 
      WHEN p_limit_type = 'wardrobe_items' THEN COALESCE(total_wardrobe_items, 0)
      WHEN p_limit_type = 'saved_outfits' THEN COALESCE(total_saved_outfits, 0)
      ELSE 0
    END
  INTO current_count
  FROM user_limits 
  WHERE user_id = p_user_id;
  
  -- Set total limits
  CASE p_limit_type
    WHEN 'wardrobe_items' THEN total_limit := 20;
    WHEN 'saved_outfits' THEN total_limit := 20;
    ELSE total_limit := 0;
  END CASE;
  
  RETURN current_count < total_limit;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_recs_jobs()
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
  insert into public.recs_jobs (user_id, run_date, status)
  select au.user_id, current_date, 'queued'
  from public.active_users_for_recs au
  on conflict (user_id, run_date) do nothing;
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_limits_row(p_user_profile_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM public.assert_own_profile(p_user_profile_id);

  INSERT INTO public.limits (user_profile_id)
  VALUES (p_user_profile_id)
  ON CONFLICT (user_profile_id) DO NOTHING;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_single_primary_avatar()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- If setting this avatar as primary, unset all other primary avatars for this user
  IF NEW.is_primary = true THEN
    UPDATE user_avatars 
    SET is_primary = false 
    WHERE user_id = NEW.user_id AND id != NEW.id;
  END IF;
  
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.exec_sql(sql text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  EXECUTE sql;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.find_pattern_counts(pattern text)
 RETURNS TABLE(table_schema text, table_name text, column_name text, match_count bigint)
 LANGUAGE plpgsql
AS $function$
DECLARE
  r record;
  v_sql text;
BEGIN
  FOR r IN
    WITH text_cols AS (
      SELECT 
        cols.table_schema,
        cols.table_name,
        cols.column_name
      FROM information_schema.columns cols
      JOIN information_schema.tables t
        ON t.table_schema = cols.table_schema
       AND t.table_name = cols.table_name
      WHERE t.table_type = 'BASE TABLE'
        AND cols.table_schema NOT IN ('pg_catalog', 'information_schema')
        AND cols.data_type IN ('text', 'character varying', 'character')
    )
    SELECT * FROM text_cols
  LOOP
    v_sql := format(
      'SELECT count(*) FROM %I.%I WHERE %I ILIKE %L',
      r.table_schema, r.table_name, r.column_name, pattern
    );
    RETURN QUERY EXECUTE
      format('SELECT %L::text, %L::text, %L::text, (%s)::bigint',
             r.table_schema, r.table_name, r.column_name, v_sql);
  END LOOP;
END $function$
;

CREATE OR REPLACE FUNCTION public.generate_and_store_recs_for_user(p_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth', 'extensions'
AS $function$
declare
  v_url       text;
  v_status    int;
  v_content   text;
  v_gender    text;
  v_weather   jsonb;
  v_payload   text;
begin
  -- HTTP таймаут для этой функции (в миллисекундах)
  perform set_config('http.timeout_msec', '180000', true);  -- 3 минуты

  select value into v_url
  from public.recs_settings
  where key = 'recs_endpoint_url';
  if v_url is null then
    raise exception using message = 'recs_endpoint_url is not set in recs_settings';
  end if;

  select up.gender into v_gender
  from public.user_profiles up
  where up.user_id = p_user_id;

  v_weather := public.get_weather_for_user(p_user_id);

  v_payload := jsonb_build_object(
    'user_id', p_user_id,
    'gender',  v_gender,
    'weather', v_weather
  )::text;

  -- http_post(url, body, content_type) -> (status, content_type, headers, content)
  select r.status, r.content
    into v_status, v_content
  from extensions.http_post(
         v_url,
         v_payload,
         'application/json'
       ) as r;

  if v_status != 200 then
    raise exception using
      message = 'Recommendation endpoint returned non-200',
      detail  = format('url=%s status=%s user_id=%s', v_url, v_status, p_user_id);
  end if;

  perform public.save_user_main_recommendation(
    p_user_id,
    v_content::jsonb,
    'algo:http'
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_feature_cost(p_user_profile_id integer, p_feature_name character varying)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
  has_subscription BOOLEAN := FALSE;
  regular_cost INTEGER := 0;
  subscription_cost INTEGER := 0;
BEGIN
  -- Check if user has active subscription
  SELECT EXISTS(
    SELECT 1 FROM user_subscriptions 
    WHERE user_profile_id = p_user_profile_id 
    AND status = 'active' 
    AND expires_at > NOW()
  ) INTO has_subscription;
  
  -- Get costs for the feature
  SELECT cost_credits, cost_subscription_credits
  INTO regular_cost, subscription_cost
  FROM feature_costs 
  WHERE feature_name = p_feature_name AND is_active = true;
  
  -- Return appropriate cost based on subscription status
  IF has_subscription THEN
    RETURN subscription_cost;
  ELSE
    RETURN regular_cost;
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_feature_cost(p_user_profile_id integer, p_feature_key text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  has_sub boolean := false;
  v_cost  integer := 0;
BEGIN
  -- активная подписка "на сейчас"
  SELECT EXISTS (
    SELECT 1
      FROM public.user_subscriptions
     WHERE user_profile_id = p_user_profile_id
       AND status = 'active'
       AND start_date <= NOW()
       AND (expires_at IS NULL OR expires_at >= NOW())
  ) INTO has_sub;

  -- стоимость из feature_costs
  SELECT CASE
           WHEN has_sub THEN COALESCE(cost_subscription_credits, cost_credits)
           ELSE COALESCE(cost_credits, 0)
         END
    INTO v_cost
    FROM public.feature_costs
   WHERE feature_name = p_feature_key
     AND is_active = TRUE
   LIMIT 1;

  RETURN COALESCE(v_cost, 0);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_profile_id(user_uuid uuid)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN (SELECT id FROM user_profiles WHERE user_id = user_uuid LIMIT 1);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_subscription_status(user_profile_id_param bigint)
 RETURNS TABLE(subscription_type character varying, status character varying, start_date timestamp with time zone, end_date timestamp with time zone, credits_included integer, is_active boolean)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    us.subscription_type,
    us.status,
    us.start_date,
    us.end_date,
    us.credits_included,
    (us.status = 'active' AND us.end_date > NOW()) as is_active
  FROM user_subscriptions us
  WHERE us.user_profile_id = user_profile_id_param
  ORDER BY us.created_at DESC
  LIMIT 1;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_weather_for_user(p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
declare
  v_row record;
  v_default_temp integer;
  v_default_condition text;
  v_month integer;
begin
  -- Получаем данные пользователя
  select
    wc.city_name,
    wc.temperature,
    wc.condition,
    wc.description,
    wc.humidity,
    wc.wind_speed,
    wc.latitude,
    wc.longitude,
    wc.updated_at
  into v_row
  from public.weather_cache wc
  where wc.user_id = p_user_id;

  -- Если данные есть и они свежие (меньше 24 часов) — возвращаем их
  if found and v_row.temperature is not null
     and v_row.updated_at > now() - interval '24 hours' then
    return jsonb_build_object(
      'city_name',   v_row.city_name,
      'temperature', v_row.temperature,
      'condition',   v_row.condition,
      'description', v_row.description,
      'humidity',    v_row.humidity,
      'wind_speed',  v_row.wind_speed,
      'latitude',    v_row.latitude,
      'longitude',   v_row.longitude,
      'updated_at',  to_char(v_row.updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
      'user_id',     p_user_id
    );
  end if;

  -- Дефолтная погода для Москвы по сезону
  v_month := extract(month from now());

  -- Примерные средние температуры для Москвы по месяцам
  case v_month
    when 1 then v_default_temp := -8; v_default_condition := 'Snow';
    when 2 then v_default_temp := -6; v_default_condition := 'Snow';
    when 3 then v_default_temp := 0; v_default_condition := 'Clouds';
    when 4 then v_default_temp := 8; v_default_condition := 'Clouds';
    when 5 then v_default_temp := 15; v_default_condition := 'Clouds';
    when 6 then v_default_temp := 20; v_default_condition := 'Clear';
    when 7 then v_default_temp := 23; v_default_condition := 'Clear';
    when 8 then v_default_temp := 21; v_default_condition := 'Clouds';
    when 9 then v_default_temp := 14; v_default_condition := 'Clouds';
    when 10 then v_default_temp := 7; v_default_condition := 'Rain';
    when 11 then v_default_temp := 1; v_default_condition := 'Clouds';
    when 12 then v_default_temp := -5; v_default_condition := 'Snow';
    else v_default_temp := 10; v_default_condition := 'Clouds';
  end case;

  -- Возвращаем дефолт для Москвы
  return jsonb_build_object(
    'city_name',   'Москва',
    'temperature', v_default_temp,
    'condition',   v_default_condition,
    'description', 'default weather for Moscow',
    'humidity',    70,
    'wind_speed',  3,
    'latitude',    55.7558,
    'longitude',   37.6176,
    'updated_at',  to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    'user_id',     p_user_id,
    'is_default',  true
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  tg_first  text := nullif(new.raw_user_meta_data->>'telegram_first_name','');
  tg_last   text := nullif(new.raw_user_meta_data->>'telegram_last_name','');
  tg_user   text := nullif(new.raw_user_meta_data->>'telegram_username','');
  tg_full   text := nullif(new.raw_user_meta_data->>'full_name','');
  photo_url text := nullif(new.raw_user_meta_data->>'telegram_photo_url','');
  full_name text := null;
begin
  -- Формируем удобочитаемое имя: "Имя Фамилия" → full_name (если есть), иначе username
  full_name := coalesce(
    nullif(trim(coalesce(tg_first,'') || ' ' || coalesce(tg_last,'')),''),
    tg_full,
    tg_user,
    'User'
  );

  insert into public.user_profiles (user_id, is_admin, full_name, avatar_url, created_at, updated_at)
  values (new.id, false, full_name, photo_url, now(), now())
  on conflict (user_id) do update
    set is_admin   = false,                    -- не даём телеграм-аккаунтам стать админом автоматически
        full_name  = excluded.full_name,       -- обновляем имя по последним данным
        avatar_url = excluded.avatar_url,
        updated_at = now();

  return new;

exception
  when others then
    perform pg_notify('handle_new_user_error', sqlerrm);
    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not new.is_admin then
    begin
      perform initialize_user_credits(new.id); -- если есть; иначе просто проглатываем
    exception
      when others then
        perform pg_notify('handle_new_user_profile_error', sqlerrm);
        -- не прерываем транзакцию
    end;
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.has_purchased_credits(p_user_profile_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.credit_transactions ct
    WHERE ct.user_profile_id = p_user_profile_id
      AND ct.amount > 0
      AND ct.reason = 'purchase_pack'  -- важно: не считаем subscription_bonus
  );
$function$
;

CREATE OR REPLACE FUNCTION public.increment_saves(outfit_id bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE outfits 
  SET saves_count = COALESCE(saves_count, 0) + 1
  WHERE id = outfit_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_views(outfit_id bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE outfits 
  SET views_count = COALESCE(views_count, 0) + 1
  WHERE id = outfit_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.init_limits_for_user(p_user_profile_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM public.assert_own_profile(p_user_profile_id);
  PERFORM public.ensure_limits_row(p_user_profile_id);

  UPDATE public.limits SET
    wardrobe_items_anlyzed = 10,
    wardrobe_items_anlyzed_updated_at = NOW(),
    vton_used = 5,
    vton_used_updated_at = NOW(),
    ai_requests = 3,
    ai_last_reset_at = NOW(),
    ai_requests_updated_at = NOW(),
    ideas_viewed = 9999,
    outfits_saved = 9999,
    ideas_viewed_updated_at = NOW(),
    outfits_saved_updated_at = NOW(),
    ideas_outfits_last_reset_at = NOW(),
    monthly_cycle_started_at = NULL,
    updated_at = NOW()
  WHERE user_profile_id = p_user_profile_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.initialize_user_credits(user_profile_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.user_credits (user_profile_id, credits_balance, total_earned)
  VALUES (user_profile_id, 30, 30)
  ON CONFLICT (user_profile_id) DO NOTHING;

  INSERT INTO public.user_limits (user_profile_id)
  VALUES (user_profile_id)
  ON CONFLICT (user_profile_id) DO NOTHING;

  -- лог "welcome_bonus" один раз
  IF NOT EXISTS (
    SELECT 1 FROM public.credit_transactions
    WHERE user_profile_id = user_profile_id
      AND reason = 'welcome_bonus'
  ) THEN
    INSERT INTO public.credit_transactions
      (user_profile_id, transaction_type, amount, reason, description)
    VALUES
      (user_profile_id, 'earn', 30, 'welcome_bonus', 'Приветственный бонус для нового пользователя');
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_current_user_admin()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
  select exists (
    select 1
    from public.user_profiles up
    where up.user_id = auth.uid()
      and coalesce(up.is_admin, false) = true
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_subscriber(p_user_profile_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  ok BOOLEAN;
BEGIN
  SELECT EXISTS(
    SELECT 1 FROM public.user_subscriptions us
    WHERE us.user_profile_id = p_user_profile_id
      AND us.status = 'active'
      AND COALESCE(us.expires_at, NOW() + interval '1 hour') > NOW()
  ) INTO ok;
  RETURN ok;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_user_admin(user_uuid uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM user_profiles 
    WHERE user_id = user_uuid AND is_admin = true
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.log_usage_event(p_user_profile_id bigint, p_feature character varying, p_action character varying, p_count integer DEFAULT 1, p_page_path text DEFAULT NULL::text, p_item_id bigint DEFAULT NULL::bigint, p_request_id uuid DEFAULT NULL::uuid, p_metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  sub BOOLEAN;
  bought BOOLEAN;
  bal INTEGER;
  l RECORD;
  anon TEXT;
BEGIN
  -- проверка «это мой профиль»
  PERFORM public.assert_own_profile(p_user_profile_id);

  -- вычисляем флаги
  sub := public.is_subscriber(p_user_profile_id);
  bought := public.has_purchased_credits(p_user_profile_id);

  SELECT credits_balance INTO bal
  FROM public.user_credits
  WHERE user_profile_id = p_user_profile_id;

  SELECT
    wardrobe_items_anlyzed,
    ai_requests,
    ideas_viewed,
    outfits_saved,
    vton_used
  INTO l
  FROM public.limits
  WHERE user_profile_id = p_user_profile_id;

  anon := public.user_anon_hash(p_user_profile_id);

  INSERT INTO public.usage_events(
    user_profile_id, user_anon_id, feature, action, count,
    is_subscriber, has_bought_credits, credits_balance, limits_snapshot,
    page_path, item_id, request_id, metadata
  ) VALUES (
    p_user_profile_id, anon, p_feature, p_action, GREATEST(1, COALESCE(p_count,1)),
    COALESCE(sub,false), COALESCE(bought,false), bal,
    to_jsonb(l),
    p_page_path, p_item_id, p_request_id, COALESCE(p_metadata, '{}'::jsonb)
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.purchase_feature_usage(p_user_profile_id integer, p_feature_type character varying)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
DECLARE
  feature_name VARCHAR(50);
  reg_cost INTEGER;
  sub_cost INTEGER;
  usage_inc INTEGER;
  has_sub BOOLEAN;
  success BOOLEAN := TRUE;
BEGIN
  -- сопоставляем внутренний тип с именем в feature_costs
  feature_name := CASE
    WHEN p_feature_type = 'wardrobe_items' THEN 'wardrobe_digitization'
    WHEN p_feature_type = 'ai_requests' THEN 'ai_assistant'
    WHEN p_feature_type = 'ideas_viewed' THEN 'ideas_viewing'
    WHEN p_feature_type = 'outfits_saved' THEN 'outfit_creation'
    ELSE p_feature_type
  END;

  -- проверяем подписку
  SELECT EXISTS (
    SELECT 1 FROM user_subscriptions
    WHERE user_profile_id = p_user_profile_id
      AND status = 'active'
      AND expires_at > NOW()
  ) INTO has_sub;

  -- читаем стоимость и количество бонусных использований
  SELECT cost_credits, cost_subscription_credits, usage_increment
    INTO reg_cost, sub_cost, usage_inc
    FROM feature_costs
    WHERE feature_name = feature_name AND is_active = TRUE;

  IF usage_inc IS NULL THEN
    RETURN FALSE;
  END IF;

  IF has_sub THEN
    IF sub_cost > 0 THEN
      SELECT spend_credits(p_user_profile_id, sub_cost, feature_name, 'Оплата за использование функции')
        INTO success;
    END IF;
  ELSE
    IF reg_cost > 0 THEN
      SELECT spend_credits(p_user_profile_id, reg_cost, feature_name, 'Оплата за использование функции')
        INTO success;
    END IF;
  END IF;

  IF NOT success THEN
    RETURN FALSE;
  END IF;

  -- увеличиваем бонусный счётчик
  IF p_feature_type = 'wardrobe_items' THEN
    UPDATE daily_usage_limits
      SET wardrobe_items_bonus_today = wardrobe_items_bonus_today + usage_inc,
          updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
  ELSIF p_feature_type = 'ai_requests' THEN
    UPDATE daily_usage_limits
      SET ai_requests_bonus_today = ai_requests_bonus_today + usage_inc,
          updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
  ELSIF p_feature_type = 'ideas_viewed' THEN
    UPDATE daily_usage_limits
      SET ideas_viewed_bonus_today = ideas_viewed_bonus_today + usage_inc,
          updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
  ELSIF p_feature_type = 'outfits_saved' THEN
    UPDATE daily_usage_limits
      SET outfits_saved_bonus_today = outfits_saved_bonus_today + usage_inc,
          updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
  END IF;

  RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.reconcile_limits(p_user_profile_id bigint)
 RETURNS limits
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  l public.limits;
  has_sub BOOLEAN;
  target_daily_ai INTEGER := 3;
  now_ts TIMESTAMPTZ := NOW();
BEGIN
  PERFORM public.assert_own_profile(p_user_profile_id);
  PERFORM public.ensure_limits_row(p_user_profile_id);

  SELECT public.is_subscriber(p_user_profile_id) INTO has_sub;

  IF has_sub THEN
    target_daily_ai := 20;

    SELECT * INTO l FROM public.limits WHERE user_profile_id = p_user_profile_id FOR UPDATE;
    IF l.monthly_cycle_started_at IS NULL
       OR (now_ts >= l.monthly_cycle_started_at + interval '1 month') THEN
      UPDATE public.limits
      SET wardrobe_items_anlyzed = 50,
          wardrobe_items_anlyzed_updated_at = now_ts,
          vton_used = 100,
          vton_used_updated_at = now_ts,
          monthly_cycle_started_at = COALESCE(l.monthly_cycle_started_at, now_ts),
          updated_at = now_ts
      WHERE user_profile_id = p_user_profile_id;
    END IF;
  END IF;

  -- daily ai reset (по смене календарной даты)
  SELECT * INTO l FROM public.limits WHERE user_profile_id = p_user_profile_id FOR UPDATE;
  IF l.ai_last_reset_at IS NULL
     OR (CURRENT_DATE > (l.ai_last_reset_at AT TIME ZONE 'UTC')::date) THEN
    UPDATE public.limits
    SET ai_requests = target_daily_ai,
        ai_last_reset_at = now_ts,
        ai_requests_updated_at = now_ts,
        updated_at = now_ts
    WHERE user_profile_id = p_user_profile_id;
  END IF;

  -- monthly ideas/outfits
  SELECT * INTO l FROM public.limits WHERE user_profile_id = p_user_profile_id FOR UPDATE;
  IF l.ideas_outfits_last_reset_at IS NULL
     OR (now_ts >= l.ideas_outfits_last_reset_at + interval '1 month') THEN
    UPDATE public.limits
    SET ideas_viewed = 9999,
        outfits_saved = 9999,
        ideas_viewed_updated_at = now_ts,
        outfits_saved_updated_at = now_ts,
        ideas_outfits_last_reset_at = now_ts,
        updated_at = now_ts
    WHERE user_profile_id = p_user_profile_id;
  END IF;

  SELECT * INTO l FROM public.limits WHERE user_profile_id = p_user_profile_id;
  RETURN l;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.record_user_activity(p_user_profile_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_today DATE := CURRENT_DATE;
BEGIN
    INSERT INTO daily_user_activity (
        user_profile_id,
        activity_date,
        first_seen_at,
        last_seen_at,
        activity_count
    ) VALUES (
        p_user_profile_id,
        v_today,
        NOW(),
        NOW(),
        1
    )
    ON CONFLICT (user_profile_id, activity_date)
    DO UPDATE SET
        last_seen_at = NOW(),
        activity_count = daily_user_activity.activity_count + 1,
        updated_at = NOW();
END;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_weather_for_user(p_user_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth', 'extensions'
AS $function$
declare
  v_lat numeric; v_lon numeric;
  v_key text; v_url text;
  v_status int; v_content text; v_json jsonb;
begin
  -- координаты строго из weather_cache
  select latitude, longitude
    into v_lat, v_lon
  from public.weather_cache
  where user_id = p_user_id;

  if v_lat is null or v_lon is null then
    return false; -- нет координат — не обновляем
  end if;

  select value into v_key
  from public.recs_settings
  where key = 'weather_api_key';
  if v_key is null then
    return false; -- нет ключа — тихо уходим
  end if;

  -- таймаут на HTTP (в миллисекундах)
  perform set_config('http.timeout_msec', '12000', true); -- 12s

  -- лёгкий джиттер, чтобы не бить ровно одновременно
  perform pg_sleep(0.1 + random() * 0.3);

  v_url := format(
    'https://api.openweathermap.org/data/2.5/weather?lat=%s&lon=%s&appid=%s&units=metric&lang=ru',
    v_lat, v_lon, v_key
  );

  -- http_get(url) -> (status, content_type, headers, content)
  begin
    select r.status, r.content
      into v_status, v_content
    from extensions.http_get(v_url) as r;
  exception when others then
    return false;
  end;

  if v_status != 200 then
    return false;
  end if;

  v_json := v_content::jsonb;

  -- апдейт полей кэша
  update public.weather_cache
     set city_name   = nullif(v_json #>> '{name}', ''),
         temperature = (v_json #>> '{main,temp}')::numeric,
         condition   = v_json #>> '{weather,0,main}',
         description = v_json #>> '{weather,0,description}',
         humidity    = (v_json #>> '{main,humidity}')::numeric,
         wind_speed  = (v_json #>> '{wind,speed}')::numeric,
         updated_at  = now()
   where user_id = p_user_id;

  return true;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.save_user_main_recommendation(p_user_id uuid, p_look_sections jsonb, p_source text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
begin
  insert into public.main_recommendations (user_id, run_date, look_sections, source)
  values (p_user_id, current_date, p_look_sections, coalesce(p_source,'algo:v1'))
  on conflict (user_id, run_date) do update
  set look_sections = excluded.look_sections,
      source       = excluded.source,
      created_at   = now();
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.spend_credits(p_user_profile_id integer, p_amount integer, p_reason text, p_description text DEFAULT NULL::text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_balance  integer;
  v_reason   text := lower(coalesce(p_reason,''));
  v_units    integer := 0;
BEGIN
  -- доступ только владельцу профиля
  PERFORM 1 FROM public.user_profiles
   WHERE id = p_user_profile_id AND user_id = auth.uid();
  IF NOT FOUND THEN RAISE EXCEPTION 'Forbidden'; END IF;

  -- нормализация
  v_reason := CASE
                WHEN v_reason IN ('ideas_viewing','ideas_views','ideas_viewed','ideas') THEN 'ideas_views'
                WHEN v_reason IN ('ai_assistant','ai_requests','ai')                     THEN 'ai_requests'
                WHEN v_reason IN ('wardrobe_digitization','wardrobe_digitizations','digitize','wardrobe_items')
                                                                                         THEN 'wardrobe_items'
                WHEN v_reason IN ('outfits_saved','outfit_creation')                     THEN 'outfits_saved'
                WHEN v_reason IN ('ai_try_on','try_on','tryon')                          THEN 'ai_try_on'
                ELSE v_reason
              END;

  -- инициализация баланса
  INSERT INTO public.user_credits (user_profile_id, credits_balance, total_earned, total_spent, created_at, updated_at)
  VALUES (p_user_profile_id, 0, 0, 0, NOW(), NOW())
  ON CONFLICT (user_profile_id) DO NOTHING;

  -- блокировка / проверка средств
  SELECT credits_balance INTO v_balance
    FROM public.user_credits
   WHERE user_profile_id = p_user_profile_id
   FOR UPDATE;
  IF p_amount IS NULL OR p_amount <= 0 OR v_balance IS NULL OR v_balance < p_amount THEN
    RETURN FALSE;
  END IF;

  -- списание
  UPDATE public.user_credits
     SET credits_balance = credits_balance - p_amount,
         total_spent     = COALESCE(total_spent,0) + p_amount,
         updated_at      = NOW()
   WHERE user_profile_id = p_user_profile_id;

  INSERT INTO public.credit_transactions
      (user_profile_id, transaction_type, amount, description, feature_used, created_at)
  VALUES (p_user_profile_id, 'spend', p_amount, p_description, v_reason, NOW());

  -- подготовка daily_usage_limits + мягкий сброс
  INSERT INTO public.daily_usage_limits
    (user_profile_id, wardrobe_items_today, ai_requests_today, ideas_viewed_today, outfits_saved_today,
     wardrobe_items_bonus_today, ai_requests_bonus_today, ideas_viewed_bonus_today, outfits_saved_bonus_today,
     last_reset_date, created_at, updated_at)
  VALUES (p_user_profile_id, 0, 0, 0, 0, 0, 0, 0, 0, CURRENT_DATE, NOW(), NOW())
  ON CONFLICT (user_profile_id) DO UPDATE
  SET wardrobe_items_today = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN 0 ELSE daily_usage_limits.wardrobe_items_today END,
      ai_requests_today    = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN 0 ELSE daily_usage_limits.ai_requests_today    END,
      ideas_viewed_today   = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN 0 ELSE daily_usage_limits.ideas_viewed_today   END,
      outfits_saved_today  = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN 0 ELSE daily_usage_limits.outfits_saved_today  END,
      wardrobe_items_bonus_today = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN 0 ELSE daily_usage_limits.wardrobe_items_bonus_today END,
      ai_requests_bonus_today    = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN 0 ELSE daily_usage_limits.ai_requests_bonus_today    END,
      ideas_viewed_bonus_today   = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN 0 ELSE daily_usage_limits.ideas_viewed_bonus_today   END,
      outfits_saved_bonus_today  = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN 0 ELSE daily_usage_limits.outfits_saved_bonus_today  END,
      last_reset_date = CASE WHEN daily_usage_limits.last_reset_date < CURRENT_DATE THEN CURRENT_DATE ELSE daily_usage_limits.last_reset_date END,
      updated_at = NOW();

  -- покупка бонусов
  IF v_reason = 'ideas_views' THEN
    v_units := GREATEST(FLOOR(p_amount / 2), 0);       -- 2 токена => +5 просмотров
    IF v_units >= 1 THEN
      UPDATE public.daily_usage_limits
         SET ideas_viewed_bonus_today = ideas_viewed_bonus_today + (5 * v_units),
             updated_at = NOW()
       WHERE user_profile_id = p_user_profile_id;
    END IF;

  ELSIF v_reason = 'ai_requests' THEN
    v_units := GREATEST(FLOOR(p_amount / 2), 0);       -- 2 токена => +1 запрос
    IF v_units >= 1 THEN
      UPDATE public.daily_usage_limits
         SET ai_requests_bonus_today = ai_requests_bonus_today + v_units,
             updated_at = NOW()
       WHERE user_profile_id = p_user_profile_id;
    END IF;

  ELSIF v_reason = 'wardrobe_items' THEN
    v_units := GREATEST(FLOOR(p_amount / 5), 0);       -- 5 токенов => +1 оцифровка
    IF v_units >= 1 THEN
      UPDATE public.daily_usage_limits
         SET wardrobe_items_bonus_today = wardrobe_items_bonus_today + v_units,
             updated_at = NOW()
       WHERE user_profile_id = p_user_profile_id;
    END IF;
  END IF;

  RETURN TRUE;
EXCEPTION
  WHEN OTHERS THEN
    RAISE EXCEPTION 'Failed to spend credits: %', SQLERRM;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.tg_set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at := now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.top_up_from_credits(p_user_profile_id bigint, p_feature text, p_need_units integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  cost_per_unit INTEGER;
  grant_per_unit INTEGER;
  packs_needed INTEGER;
  bal INTEGER;
BEGIN
  PERFORM public.assert_own_profile(p_user_profile_id);

  IF p_feature = 'wardrobe_items_anlyzed' THEN
    cost_per_unit := 5; grant_per_unit := 1;
  ELSIF p_feature = 'ai_requests' THEN
    cost_per_unit := 2; grant_per_unit := 5;
  ELSIF p_feature = 'vton_used' THEN
    cost_per_unit := 3; grant_per_unit := 1;
  ELSE
    RETURN FALSE;
  END IF;

  packs_needed := CEIL(p_need_units::NUMERIC / grant_per_unit);

  SELECT credits_balance
    INTO bal
  FROM public.user_credits
  WHERE user_profile_id = p_user_profile_id
  FOR UPDATE;
  IF bal IS NULL OR bal < packs_needed * cost_per_unit THEN
    RETURN FALSE;
  END IF;

  UPDATE public.user_credits
  SET credits_balance = credits_balance - (packs_needed * cost_per_unit),
      updated_at = NOW()
  WHERE user_profile_id = p_user_profile_id;

  INSERT INTO public.credit_transactions(
    user_profile_id, 
    transaction_type,
    amount, 
    reason, 
    description,
    feature_used
  )
  VALUES (
    p_user_profile_id, 
    'spend',
    -(packs_needed * cost_per_unit), 
    'auto_topup', 
    CONCAT('Top-up for ', p_feature),
    p_feature
  );

  IF p_feature = 'wardrobe_items_anlyzed' THEN
    UPDATE public.limits
    SET wardrobe_items_anlyzed = wardrobe_items_anlyzed + (packs_needed * grant_per_unit),
        wardrobe_items_anlyzed_updated_at = NOW(),
        updated_at = NOW()
    WHERE user_profile_id = p_user_profile_id;
  ELSIF p_feature = 'ai_requests' THEN
    UPDATE public.limits
    SET ai_requests = ai_requests + (packs_needed * grant_per_unit),
        ai_requests_updated_at = NOW(),
        updated_at = NOW()
    WHERE user_profile_id = p_user_profile_id;
  ELSE
    UPDATE public.limits
    SET vton_used = vton_used + (packs_needed * grant_per_unit),
        vton_used_updated_at = NOW(),
        updated_at = NOW()
    WHERE user_profile_id = p_user_profile_id;
  END IF;

  RETURN TRUE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.trg_init_limits()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  PERFORM public.init_limits_for_user(NEW.id);
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_avatars_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_user_fittings_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_wardrobe_user_items_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.use_feature(p_user_profile_id bigint, p_feature character varying, p_count integer DEFAULT 1)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  l public.limits;
  available INTEGER := 0;
  ok BOOLEAN := FALSE;
BEGIN
  PERFORM public.assert_own_profile(p_user_profile_id);
  PERFORM public.reconcile_limits(p_user_profile_id);

  SELECT * INTO l FROM public.limits WHERE user_profile_id = p_user_profile_id FOR UPDATE;

  IF p_feature = 'wardrobe_items_anlyzed' THEN
    available := l.wardrobe_items_anlyzed;
  ELSIF p_feature = 'ai_requests' THEN
    available := l.ai_requests;
  ELSIF p_feature = 'ideas_viewed' THEN
    available := l.ideas_viewed;
  ELSIF p_feature = 'outfits_saved' THEN
    available := l.outfits_saved;
  ELSIF p_feature = 'vton_used' THEN
    available := l.vton_used;
  ELSE
    RETURN FALSE;
  END IF;

  IF available >= p_count THEN
    IF p_feature = 'wardrobe_items_anlyzed' THEN
      UPDATE public.limits SET wardrobe_items_anlyzed = wardrobe_items_anlyzed - p_count,
        wardrobe_items_anlyzed_updated_at = NOW(), updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
    ELSIF p_feature = 'ai_requests' THEN
      UPDATE public.limits SET ai_requests = ai_requests - p_count,
        ai_requests_updated_at = NOW(), updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
    ELSIF p_feature = 'ideas_viewed' THEN
      UPDATE public.limits SET ideas_viewed = ideas_viewed - p_count,
        ideas_viewed_updated_at = NOW(), updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
    ELSIF p_feature = 'outfits_saved' THEN
      UPDATE public.limits SET outfits_saved = outfits_saved - p_count,
        outfits_saved_updated_at = NOW(), updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
    ELSE
      UPDATE public.limits SET vton_used = vton_used - p_count,
        vton_used_updated_at = NOW(), updated_at = NOW()
      WHERE user_profile_id = p_user_profile_id;
    END IF;
    RETURN TRUE;
  END IF;

  IF p_feature IN ('wardrobe_items_anlyzed','ai_requests','vton_used') THEN
    ok := public.top_up_from_credits(p_user_profile_id, p_feature, p_count - available);
    IF ok THEN
      RETURN public.use_feature(p_user_profile_id, p_feature, p_count);
    END IF;
  END IF;

  RETURN FALSE;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.user_anon_hash(p_user_profile_id bigint)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select md5(p_user_profile_id::text || ':' || coalesce(current_setting('app.anon_salt', true), 'default-salt'));
$function$
;


-- Foreign Keys (deferred to avoid circular dependency issues)
ALTER TABLE "basic_item_materials" ADD FOREIGN KEY ("basic_item_id") REFERENCES "basic_wardrobe_items"("id");
ALTER TABLE "basic_item_materials" ADD FOREIGN KEY ("basic_material_id") REFERENCES "basic_materials"("id");
ALTER TABLE "combination_elements" ADD FOREIGN KEY ("basic_item_id") REFERENCES "basic_wardrobe_items"("id");
ALTER TABLE "combination_elements" ADD FOREIGN KEY ("basic_material_id") REFERENCES "basic_materials"("id");
ALTER TABLE "combination_elements" ADD FOREIGN KEY ("combination_id") REFERENCES "combinations"("id");
ALTER TABLE "credit_transactions" ADD FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles"("id");
ALTER TABLE "daily_user_activity" ADD FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles"("id");
ALTER TABLE "limits" ADD FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles"("id");
ALTER TABLE "outfit_items" ADD FOREIGN KEY ("outfit_id") REFERENCES "outfits"("id");
ALTER TABLE "outfit_items" ADD FOREIGN KEY ("wardrobe_item_id") REFERENCES "wardrobe_items"("id");
ALTER TABLE "section_looks" ADD FOREIGN KEY ("look_id") REFERENCES "user_looks"("id");
ALTER TABLE "section_looks" ADD FOREIGN KEY ("section_id") REFERENCES "looks_sections"("id");
ALTER TABLE "usage_events" ADD FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles"("id");
ALTER TABLE "user_credits" ADD FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles"("id");
ALTER TABLE "user_events" ADD FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles"("id");
ALTER TABLE "user_likes" ADD FOREIGN KEY ("outfit_id") REFERENCES "outfits"("id");
ALTER TABLE "user_subscriptions" ADD FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles"("id");
ALTER TABLE "wardrobe_items" ADD FOREIGN KEY ("basic_item_id") REFERENCES "wardrobe_items"("id");
ALTER TABLE "wardrobe_items" ADD FOREIGN KEY ("basic_item_id") REFERENCES "basic_wardrobe_items"("id");
ALTER TABLE "wardrobe_items" ADD FOREIGN KEY ("basic_material_id") REFERENCES "basic_materials"("id");
