-- Migration 006: separate id namespaces for wardrobe_items and wardrobe_user_items.
--
-- Background: both tables declare `id BIGINT GENERATED BY DEFAULT AS IDENTITY`
-- with independent sequences. The numeric id ranges overlap, so any code that
-- uses a bare int id across both sources (AI prompts, FAISS results, recommendation
-- enrichment, dislike tracking) can silently pick up the wrong row. We already
-- route by an explicit item_source at the application layer (see migrations/004
-- and app/api/recommendations.py), but keeping the numeric ranges disjoint is
-- a cheap safety net: any future place that forgets to pass item_source will
-- simply find nothing instead of returning a wrong row.
--
-- Strategy: shift the wardrobe_items identity sequence to start from 1_000_000_000.
-- Existing rows keep their ids. Only inserts made after this migration get the
-- new range. wardrobe_user_items keeps its normal 1..N range — users will not
-- add a billion wardrobe items each in the foreseeable future.
--
-- Idempotent: skips the RESTART if the sequence is already past the offset.

DO $$
DECLARE
    seq_name text;
    current_max bigint;
    target_start bigint := 1000000000;
BEGIN
    SELECT pg_get_serial_sequence('public.wardrobe_items', 'id') INTO seq_name;
    IF seq_name IS NULL THEN
        RAISE NOTICE 'wardrobe_items.id is not an identity column — skipping';
        RETURN;
    END IF;

    SELECT COALESCE(MAX(id), 0) FROM public.wardrobe_items INTO current_max;

    IF current_max >= target_start THEN
        RAISE NOTICE 'wardrobe_items.id already beyond % (max=%) — skipping', target_start, current_max;
        RETURN;
    END IF;

    EXECUTE format('ALTER SEQUENCE %s RESTART WITH %s', seq_name, target_start);
    RAISE NOTICE 'wardrobe_items sequence restarted at %', target_start;
END $$;
