-- 025: подтянуть отставшую последовательность outfit_items.id.
--
-- Найдено 2026-08-17 при наполнении витрины: outfit_items.id — GENERATED BY
-- DEFAULT AS IDENTITY, но его последовательность стояла на 238 при max(id) =
-- 444. Наследство переезда с Supabase: строки залили с явными id, а
-- последовательность не подкрутили.
--
-- Чем это грозило. В диапазоне 239..444 занято 31 id из 206, причём блоками
-- (вещи старых образов вставлялись подряд). nextval идёт вперёд и периодически
-- въезжает в занятый блок:
--   * seed_vibes.py вставлял с ON CONFLICT DO NOTHING — конфликт по ПЕРВИЧНОМУ
--     ключу проглатывался молча, и 11 курируемых образов из 72 потеряли все свои
--     вещи разом (блок занятых id накрывает как раз 3-4 вещи одного образа);
--   * create_outfit (POST /api/outfits) вставляет БЕЗ ON CONFLICT — там это
--     duplicate key, то есть сохранение образа у обычного пользователя падает.
--
-- Правим только эту последовательность: обход всех identity/serial колонок на
-- проде показал ровно одну отстающую, а массовый setval по базе — это лечение
-- того, что не болит. Запрос для повторной проверки (deptype='a' для identity
-- НЕ годится, у него тип зависимости 'i' — первый вариант скана поэтому ничего
-- и не нашёл):
--
--   SELECT c.table_name, c.column_name,
--          pg_get_serial_sequence(format('public.%I', c.table_name), c.column_name)
--   FROM information_schema.columns c
--   WHERE c.table_schema='public'
--     AND (c.is_identity='YES' OR c.column_default LIKE 'nextval%');
--
-- Идемпотентно: GREATEST не даёт откатить последовательность назад, если она
-- уже впереди max(id).

BEGIN;

SELECT setval(
    pg_get_serial_sequence('public.outfit_items', 'id'),
    GREATEST(
        (SELECT COALESCE(max(id), 1) FROM outfit_items),
        (SELECT last_value FROM pg_sequences
         WHERE schemaname = 'public'
           AND sequencename = 'outfit_items_id_seq')
    )
);

COMMIT;
