-- 050: у user_likes.id должно быть значение по умолчанию.
--
-- Найдено e2e-прогоном 2026-09-28 на базе, накатанной из репозитория с нуля:
-- 001_schema.sql объявляет "id" BIGINT NOT NULL без identity и без sequence, а
-- оба места, где ставится лайк, id не передают:
--   * POST /api/outfits/like        (outfits.py, лайк в ленте идей);
--   * POST /api/rec-event like_outfit (rec_events.py, лайк образа на главной).
-- Итог на такой схеме — 500 на КАЖДЫЙ лайк. Фронт ленты глотает ошибку
-- (catch (_) {} в app/app/inspiration/page.tsx), так что снаружи это выглядит
-- как «сердечко не залипает», а не как авария.
--
-- Была ли так же сломана боевая база — из репозитория не видно: при переезде
-- с Supabase колонка могла сохранить свой identity. Поэтому миграция ничего не
-- делает, если значение по умолчанию уже есть (identity или nextval), и
-- чинит, если его нет. Проверить прод руками:
--   SELECT is_identity, column_default FROM information_schema.columns
--   WHERE table_name = 'user_likes' AND column_name = 'id';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'user_likes' AND column_name = 'id'
          AND is_identity = 'NO' AND column_default IS NULL
    ) THEN
        ALTER TABLE public.user_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        -- Строки с явными id уже могут быть: начать после максимального.
        PERFORM setval(pg_get_serial_sequence('public.user_likes', 'id'),
                       GREATEST((SELECT COALESCE(max(id), 0) FROM public.user_likes), 1));
    END IF;
END $$;
