-- ПОЛНЫЙ SQL ЗАПРОС ДЛЯ ИМПОРТА ДАННЫХ ГАРДЕРОБА В SUPABASE
-- Этот файл содержит всё необходимое для создания таблицы и вставки данных

-- Шаг 1: Создаем таблицу
DROP TABLE IF EXISTS wardrobe_items CASCADE;

CREATE TABLE wardrobe_items (
    id BIGSERIAL PRIMARY KEY,
    item_name TEXT NOT NULL,
    item_type TEXT,
    size_type TEXT,
    material TEXT,
    style TEXT,
    has_print TEXT,
    color TEXT,
    shade TEXT,
    has_details TEXT,
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Шаг 2: Создаем индексы для быстрого поиска
CREATE INDEX idx_wardrobe_items_name ON wardrobe_items(item_name);
CREATE INDEX idx_wardrobe_items_type ON wardrobe_items(item_type);
CREATE INDEX idx_wardrobe_items_color ON wardrobe_items(color);
CREATE INDEX idx_wardrobe_items_material ON wardrobe_items(material);

-- Шаг 3: Настраиваем безопасность (RLS)
ALTER TABLE wardrobe_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for authenticated users" ON wardrobe_items
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow read for anonymous users" ON wardrobe_items
    FOR SELECT USING (auth.role() = 'anon');

-- Шаг 4: Вставляем все данные из CSV
INSERT INTO wardrobe_items (item_name, item_type, size_type, material, style, has_print, color, shade, has_details, url) VALUES
('light-upper_blouse_beige', 'blouse', 'Regular', 'Satin', 'Classic/evening', 'N', 'beige ', 'Light', 'N', 'https://loverepublic.ru/catalog/odezhda/bluzy/274071/'),
('light-upper_blouse_beige-with-bows', 'blouse', 'Short', 'Satin', 'Classic/evening', 'N', 'beige with bows', 'Light', 'Y', 'https://loverepublic.ru/catalog/odezhda/bluzy/269192/'),
('light-upper_blouse_beige-with-ties', 'blouse', 'Regular', 'nan', 'nan', 'N', 'beige with ties', 'Light', 'nan', 'https://passywear.ru/tproduct/470231804-696136030881-bluza-na-zavyazkah-beige'),
('light-upper_blouse_black-transparent-with-beads', 'blouse', 'Short', 'Chiffon', 'Evening', 'N', 'black transparent with beads', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/trikotazh/dzhempery/270048/'),
('light-upper_blouse_beige-with-bows', 'blouse', 'Short', 'Satin', 'Classic/evening', 'N', 'black_with_bows', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/bluzy/269200/'),
('light-upper_blouse_brown-with-flounces', 'blouse', 'Regular', 'Viscose', 'Classic/evening', 'N', 'brown with flounces', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/bluzy/265695/'),
('light-upper_blouse_burgundy', 'blouse', 'Regular', 'Cotton', 'Classic/evening', 'N', 'burgundy', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/23947_8486_334-bordovyi'),
('light-upper_blouse_grey', 'blouse', 'Regular', 'Tencel', 'Evening', 'N', 'grey', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/bluzy/268646/'),
('light-upper_blouse_white', 'blouse', 'Regular', 'Cotton', 'Casual', 'N', 'white', 'Light', 'N', 'https://presentandsimple.com/catalog/rubaski/rubaska-chester-iz-100-xlopka-107324'),
('light-upper_blouse_white-with-flounces', 'blouse', 'Regular', 'Cotton', 'Classic/evening', 'N', 'white_with_frills', 'Light', 'Y', 'https://loverepublic.ru/catalog/odezhda/bluzy/274569/'),
('light-upper_lonsleeve_white', 'lonsleeve', 'Regular', 'Cotton', 'Classic/evening', 'N', 'beige', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/20659_8188_679-belyi'),
('light-upper_lonsleeve_khaki', 'lonsleeve', 'Regular', 'Cotton', 'Classic/evening', 'N', 'black', 'Dark', 'N', 'https://presentandsimple.com/catalog/longslivy/longsliv-snug-iz-italyanskogo-xlopka-110351'),
('light-upper_lonsleeve_black-asymmetrical', 'lonsleeve', 'Short', 'Polyamide, lurex', 'Classic/evening', 'N', 'black_asymmetrical', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/trikotazh/dzhempery/271343/'),
('light-upper_lonsleeve_brown', 'lonsleeve', 'Regular', 'Lyocell,wool', 'Classic/evening', 'N', 'brown', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/20659_8188_679-koricnevyi'),
('light-upper_lonsleeve_khaki', 'lonsleeve', 'nan', 'nan', 'nan', 'nan', 'khaki', 'Colourful', 'nan', 'https://lookonline.ru/product/longsliv-oblegaiushhii-4-xaki'),
('light-upper_lonsleeve_light-grey', 'lonsleeve', 'Regular', 'Cotton', 'Classic', 'N', 'light_grey', 'Colourful', 'N', 'https://loverepublic.ru/catalog/odezhda/futbolki/271423/'),
('light-upper_lonsleeve_light-grey', 'lonsleeve', 'Regular', 'Cotton', 'Classic', 'N', 'light_grey_oversized', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/16762_0153_605-cernyi'),
('light-upper_lonsleeve_white', 'lonsleeve', 'Regular', 'Cotton', 'Classic', 'N', 'white', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/23106_3596_270-belyi'),
('light-upper_lonsleeve_white-with-blue-seams', 'lonsleeve', 'nan', 'nan', 'nan', 'nan', 'white with blue seams', 'Light', 'nan', 'https://passywear.ru/tproduct/470231804-775249232041-longsliv-s-relefami-i-goluboi-strochkoi'),
('light-upper_t-shirt_black', 'shirt', 'Regular', 'Viscose, nylon', 'Casual', 'N', 'black', 'Dark', 'N', 'https://yollo.com/women/shirts-blouses/bluza-s-ostrokonechnym-vorotnikom/?color=3'),
('light-upper_shirt_black-checkered', 'shirt', 'nan', 'nan', 'nan', 'nan', 'black_checkered', 'Dark', 'nan', 'https://toptop.ru/catalog/clothes/shirts-blouses/shirts/2008723123271'),
('light-upper_shirt_blue', 'shirt', 'Regular', 'Cotton', 'Casual', 'N', 'blue', 'Colourful', 'N', 'https://yollo.com/women/shirts-blouses/rubashka-s-zakrytoy-plankoy/'),
('light-upper_shirt_blue-cropped', 'shirt', 'nan', 'nan', 'nan', 'nan', 'blue_cropped', 'Colourful', 'nan', 'https://rosi-store.ru/catalog/sale/ukorochennaya-rubashka-iz-poplina_4127/'),
('light-upper_t-shirt_beige', 'shirt', 'Regular', 'Polyester', 'Classic/evening', 'N', 'corduroy_beige', 'Light', 'N', 'https://nuw.store/catalog/rubashki_i_overshoty/overshot_corduroy_work-color-bezhevyj/'),
('light-upper_shirt_grey-brown', 'shirt', 'Regular', 'Cupro', 'Classic/evening', 'N', 'grey', 'Colourful', 'N', 'https://loverepublic.ru/catalog/odezhda/bluzy/273272/'),
('light-upper_shirt_grey-brown', 'shirt', 'Regular', 'Lyocell,wool', 'Evening', 'N', 'grey-brown', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/22884_1871_646-sero_koricnevyi'),
('light-upper_shirt_white', 'shirt', 'Regular', 'Cotton', 'Casual', 'N', 'white', 'Light', 'N', 'https://loverepublic.ru/catalog/odezhda/bluzy/264129/'),
('light-upper_shirt_blue-cropped', 'shirt', 'Short', 'Polyester,cotton', 'Classic/evening', 'N', 'white_cropped', 'Light', 'N', 'https://loverepublic.ru/catalog/odezhda/bluzy/268769/'),
('light-upper_t-shirt_beige', 't-shirt', 'Regular', 'Lyocell,wool', 'Classic/evening', 'N', 'beige', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/22465_3806_679-kamennyi'),
('light-upper_t-shirt_black', 't-shirt', 'Regular', 'Cotton', 'Casual', 'N', 'black', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/23574_3605_271-cernyi'),
('light-upper_t-shirt_brown', 't-shirt', 'Regular', 'Cotton', 'Casual', 'N', 'brown', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/futbolki/274224/'),
('light-upper_t-shirt_grey-oversized', 't-shirt', 'Regular', 'Cotton', 'Casual', 'N', 'grey_oversized', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/21945_7784_107-temno_seryi'),
('light-upper_t-shirt_khaki-oversized', 't-shirt', 'Regular', 'Cotton', 'Casual', 'N', 'khaki_oversized', 'Colourful', 'N', 'https://presentandsimple.com/catalog/futbolki/futbolka-base-iz-plotnogo-xlopka-108104'),
('light-upper_t-shirt_white', 't-shirt', 'Regular', 'Cotton,modal', 'Casual', 'N', 'white', 'Light', 'N', 'https://loverepublic.ru/catalog/odezhda/futbolki/275990/'),
('light-upper_t-shirt_white-oversized', 't-shirt', 'Regular', 'Cotton', 'Casual', 'N', 'white_oversized', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/21944_7783_107-belyi'),
('light-upper_tank-top_brown', 'tank-top', 'Short', 'Cotton', 'Casual', 'N', 'black_cropped', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/11197_7751_386-belyi'),
('light-upper_tank-top_brown', 'tank-top', 'Regular', 'Cotton', 'Casual', 'N', 'brown', 'Dark', 'N', 'https://rosi-store.ru/catalog/futbolki-i-longslivy/top-v-rubchik_6538/'),
('light-upper_tank-top_brown-bodysuit', 'tank-top', 'Regular', 'Polyamide, elastane', 'Casual', 'N', 'brown bodysuit', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/13165_0996_362-koricnevyi'),
('light-upper_tank-top_dark-grey', 'tank-top', 'nan', 'nan', 'nan', 'N', 'dark grey', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/20471_8741_844-temno_seryi_melanz'),
('light-upper_tank-top_dark-grey-bodysuit', 'tank-top', 'Regular', 'Polyamide, elastane', 'Casual', 'N', 'dark grey bodysuit', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/11475_7368_362-temno_seryi'),
('light-upper_tank-top_grey', 'tank-top', 'Regular', 'Cotton', 'Casual', 'N', 'grey', 'Colourful', 'N', 'https://rosi-store.ru/catalog/futbolki-i-longslivy/top-v-rubchik/'),
('light-upper_tank-top_white', 'tank-top', 'nan', 'nan', 'nan', 'N', 'white', 'Light', 'N', 'https://rosi-store.ru/catalog/futbolki-i-longslivy/mayka-v-rubchik_6544/'),
('light-upper_tank-top_white', 'tank-top', 'Short', 'Cotton', 'Casual', 'N', 'white_cropped', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/11197_7751_386-belyi'),
('upper_cardigan_beige', 'cardigan', 'Regular', 'Silk,viscose', 'Classic/casual', 'N', 'beige', 'Light', 'N', 'https://presentandsimple.com/catalog/kardigany/kardigan-astrid-iz-selka-i-viskozy-103101'),
('upper_cardigan_black', 'cardigan', 'Regular', 'Viscose', 'Classic/casual', 'N', 'black', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/trikotazh/dzhempery/269915/'),
('upper_cardigan_black-cropped', 'cardigan', 'Short', 'Viscose,polyester', 'Classic/casual', 'N', 'black_cropped_with_zipper', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/trikotazh/dzhempery/271421/'),
('upper_cardigan_brown', 'cardigan', 'nan', 'nan', 'nan', 'N', 'brown', 'Dark', 'nan', 'https://rosi-store.ru/catalog/clothes-knitwear/kardigan-iz-shersti_8380/'),
('upper_cardigan_grey ', 'cardigan', 'Long', 'Cotton', 'Classic/casual', 'N', 'grey ', 'Colourful', 'N', 'https://rosi-store.ru/catalog/clothes-knitwear/kardigan-iz-shersti/'),
('upper_cardigan_leopard ', 'cardigan', 'Regular', 'Mohair, wool', 'Classic/casual', 'Y', 'leopard ', 'Colourful', 'N', 'https://rosi-store.ru/catalog/clothes-knitwear/kardigan-leo-iz-mokhera-i-shersti/'),
('upper_cardigan_light-grey', 'cardigan', 'Regular', 'Viscose', 'Classic/casual', 'N', 'light_grey', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/22891_2883_961-svetlo_seryi_melanz'),
('upper_cardigan_white', 'cardigan', 'Regular', 'Cotton', 'Classic/casual', 'N', 'white', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/22421_0530_836-molocnyi'),
('upper_hoodie_beige', 'hoodie', 'Regular', 'nan', 'Casual', 'Y', 'beige', 'Light', 'N', 'https://passywear.ru/catalog/women/tproduct/835059773-537024949731-hudi-tsement'),
('upper_hoddie_black', 'hoddie', 'Regular', 'nan', 'Casual', 'Y', 'black', 'Dark', 'N', 'https://passywear.ru/tproduct/470231804-394188341061-hudi-saint'),
('upper_hoodie_black-with-a-zipper', 'hoodie', 'Short', 'Cotton', 'Casual', 'Y', 'black_with_a_zipper', 'Dark', 'N', 'https://you-wanna.ru/catalog/jersey/sweatshirts/product/220300310RF24/'),
('upper_hoddie_blue-with-a-zipper', 'hoddie', 'nan', 'nan', 'nan', 'nan', 'blue_with_a_zipper', 'Colourful', 'nan', 'https://rosi-store.ru/catalog/svitshoty-i-khudi/zip-khudi-need-coffee/'),
('upper_hoodie_green', 'hoodie', 'Regular', 'Cotton', 'Casual', 'Y', 'green', 'Colourful', 'N', 'https://nuw.store/catalog/tolstovki/khudi_slogan_1-color-temno-zelenyj/'),
('upper_hoddie_grey-with-a-zipper', 'hoddie', 'nan', 'nan', 'nan', 'nan', 'grey_with_a_zipper', 'Colourful', 'nan', 'https://lookonline.ru/product/tolstovka-oversize-na-molnii-s-potertostiami-seryi'),
('upper_hoddie_light-grey-with-a-zipper', 'hoddie', 'nan', 'nan', 'nan', 'nan', 'light-grey_with_a_zipper', 'Colourful', 'nan', 'https://rosi-store.ru/catalog/svitshoty-i-khudi/zip-khudi-comfortable-living/'),
('upper_pullover_beige', 'pullover', 'Regular', 'Cashmere', 'Classic/casual', 'N', 'beige', 'Light', 'N', 'https://presentandsimple.com/catalog/dzempery/dzemper-sky-iz-100-kasemira-loro-piana-101305'),
('upper_pullover_beige-high-necked', 'pullover', 'nan', 'nan', 'nan', 'nan', 'beige_high_necked', 'Light', 'nan', 'https://yollo.com/women/jumpers/djemper-s-vysokim-vorotom/'),
('upper_pullover_beige', 'pullover', 'Short', 'Cotton', 'Classic/casual', 'N', 'beige_oversized', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/23520_3367_591-molocnyi'),
('upper_pullover_black', 'pullover', 'Regular', 'Cashmere', 'Classic/casual', 'N', 'black', 'Dark', 'N', 'https://presentandsimple.com/catalog/dzempery/dzemper-clear-cashmere-iz-100-kasemira-101334'),
('upper_pullover_black-with-scuffs', 'pullover', 'nan', 'nan', 'nan', 'nan', 'black_with_scuffs', 'Dark', 'nan', 'https://you-wanna.ru/catalog/jersey/sweaters/product/FM411023KK/'),
('upper_pullover_brown', 'pullover', 'nan', 'nan', 'nan', 'nan', 'brown', 'Dark', 'nan', 'https://you-wanna.ru/catalog/jersey/sweaters/product/330200710RF24B/'),
('upper_pullover_brown', 'pullover', 'Short', 'Viscose,polyester', 'Classic/casual', 'N', 'brown_cropped', 'Dark', 'N', 'https://lichi.com/ru/ru/product/47721'),
('upper_pullover_dark-blue', 'pullover', 'Regular', 'Cashmere', 'Classic/casual', 'N', 'dark_blue', 'Colourful', 'N', 'https://presentandsimple.com/catalog/dzempery/dzemper-sky-iz-100-kasemira-loro-piana-101262'),
('upper_pullover_grey', 'pullover', 'Regular', 'Wool', 'Classic/casual', 'N', 'grey', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/21813_0453_796-seryi_melanz'),
('upper_pullover_grey', 'pullover', 'Regular', 'Mohair, wool', 'Classic/casual', 'N', 'white', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/21720_1414_929-molocnyi'),
('upper_suit-jacket_beige', 'suit-jacket', 'Regular', 'Polyester,viscose', 'Classic/casual', 'N', 'beige', 'Light', 'N', 'https://presentandsimple.com/catalog/zakety/zaket-gracy'),
('upper_suit-jacket_black', 'suit-jacket', 'Regular', 'Polyester,viscose', 'Classic/casual', 'N', 'black', 'Dark', 'N', 'https://studio-29.ru/catalog/pidzhaki_zhakety/113554/'),
('upper_suit-jacket_black-striped', 'suit-jacket', 'Regular', 'Polyester,viscose', 'Classic/casual', 'Y', 'black_striped', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/21850_7990_952-cernyi_belyi'),
('upper_suit-jacket_brown-cropped', 'suit-jacket', 'nan', 'nan', 'nan', 'nan', 'brown_cropped', 'Dark', 'nan', 'https://lookonline.ru/product/zaket-ukorocennyi-250-koricnevyi'),
('upper_suit-jacket_burgundy', 'suit-jacket', 'Regular', 'Polyester,viscose', 'Classic/casual', 'N', 'burgundy', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/17803_0490_325-vinnyi'),
('upper_suit-jacket_grey', 'suit-jacket', 'Regular', 'Polyester,viscose', 'Classic/casual', 'N', 'grey', 'Colourful', 'N', 'https://lime-shop.com/ru_ru/product/24246_0490_163-svetlo_seryi_melanz'),
('upper_suit-jacket_grey-cropped', 'suit-jacket', 'Short', 'Terylene', 'Classic/casual', 'N', 'grey_cropped', 'Colourful', 'N', 'https://toptop.ru/catalog/clothes/blazers/2008723116440'),
('upper_sweatshirt_beige-with-the-inscription', 'sweatshirt', 'nan', 'nan', 'nan', 'nan', 'beige_with_the_inscription', 'Light', 'nan', 'https://rosi-store.ru/catalog/svitshoty-i-khudi/svitshot-iz-futera-rosi-sport/'),
('upper_sweatshirt_black', 'sweatshirt', 'Regular', 'Cotton', 'Casual', 'N', 'black', 'Dark', 'N', 'https://befree.ru/zhenskaya/product/BF2511123003/50'),
('upper_sweatshirt_black-with-the-inscription', 'sweatshirt', 'Regular', 'Cotton', 'Casual', 'Y', 'black_with_the_inscription', 'Dark', 'N', 'https://toptop.ru/catalog/clothes/sweatshirts/sweatshirt/2008723120843'),
('upper_sweatshirt_brown', 'sweatshirt', 'Regular', 'Polyester,modal', 'Casual', 'N', 'brown', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/23774_3804_696-temno_koricnevyi'),
('upper_sweatshirt_grey', 'sweatshirt', 'nan', 'nan', 'nan', 'nan', 'grey', 'Colourful', 'nan', 'https://lime-shop.com/ru_ru/product/20793_8113_948-svetlo_seryi_melanz'),
('upper_sweatshirt_white', 'sweatshirt', 'Regular', 'Cotton', 'Casual', 'N', 'white', 'Light', 'N', 'https://befree.ru/zhenskaya/product/BF2511123003/60'),
('upper_turtleneck_beige', 'turtleneck', 'nan', 'nan', 'nan', 'nan', 'beige', 'Light', 'nan', 'https://rosi-store.ru/catalog/clothes-knitwear/vodolazka-iz-shersti-i-kashemira_8310/'),
('upper_turtleneck_black', 'turtleneck', 'nan', 'nan', 'nan', 'nan', 'black', 'Dark', 'nan', 'https://rosi-store.ru/catalog/clothes-knitwear/vodolazka-iz-shersti-i-kashemira_8309/'),
('upper_turtleneck_ginger', 'turtleneck', 'Regular', 'Wool, cashmere and viscose', 'Classic/casual', 'N', 'ginger', 'Colourful', 'N', 'https://presentandsimple.com/catalog/svitery/sviter-simple-iz-italyanskoi-sersti-kasemira-i-viskozy'),
('upper_turtleneck_grey', 'turtleneck', 'Regular', 'Cashmere', 'Classic/casual', 'N', 'grey', 'Colourful', 'N', 'https://presentandsimple.com/catalog/svitery/sviter-just-cashmere-iz-100-kasemira-102225'),
('upper_turtleneck_white', 'turtleneck', 'Regular', 'Polyester,viscose', 'Classic/casual', 'N', 'white', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/22887_3132_322-molocnyi'),
('upper_vest_beige', 'vest', 'Regular', 'Wool, cotton', 'Classic/casual', 'N', 'beige', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/21894_0431_630-kremovyi_melanz'),
('upper_vest_black-suit', 'vest', 'nan', 'nan', 'nan', 'nan', 'black_suit', 'Dark', 'nan', 'https://presentandsimple.com/catalog/zilety/zilet-julia-iz-sersti-merinosa'),
('upper_vest_grey', 'vest', 'nan', 'nan', 'nan', 'nan', 'grey', 'Colourful', 'nan', 'https://lime-shop.com/ru_ru/product/21894_0431_630-kremovyi_melanz'),
('upper_vest_grey-suit', 'vest', 'Regular', 'Polyester,viscose', 'Classic', 'N', 'grey_suit', 'Colourful', 'N', 'https://presentandsimple.com/catalog/zilety/zilet-rene'),
('evening_dress_short_black', 'dress', 'Short', 'Cotton', 'Casual', 'N', 'short_black', 'Dark', 'N', 'https://studio-29.ru/catalog/platya/113877/'),
('evening_dress_short_black-balloon', 'dress', 'Short', 'Polyester', 'Evening', 'N', 'short_black-balloon', 'Dark', 'Y', 'https://studio-29.ru/catalog/platya/116152/'),
('evening_dress_short_brown', 'dress', 'Short', 'Polyester', 'Evening', 'N', 'short_brown', 'Dark', 'Y', 'https://you-wanna.ru/catalog/platyaandsarafani/dress_dresses/product/880105710RF24S/'),
('evening_dress_short_tweed', 'dress', 'Short', 'Tweed', 'Classic', 'N', 'short_tweed', 'Dark', 'Y', 'https://yollo.com/women/dresses/plate-iz-tvida-na-pugovicah/?color=3'),
('evening_dress_short_white-peas', 'dress', 'Short', 'Polyester', 'Evening', 'Y', 'short_white-peas', 'Light', 'Y', 'https://lookonline.ru/product/plate-mini-s-glubokim-vyrezom-2-belyi'),
('evening_dress_slim_beige-with-seams', 'dress', 'Long', 'Cotton', 'Classic', 'N', 'slim_beige-with-seams', 'Light', 'Y', 'https://xsai.store/women/tproduct/607434350-624717339292-long-dress-01'),
('evening_dress_slim_black', 'dress', 'Long', 'Polyester', 'Casual', 'N', 'slim_black', 'Dark', 'N', 'https://xsai.store/women/tproduct/607434350-474264100482-longsleeve-dress'),
('evening_dress_slim_black-barhat', 'dress', 'Regular', 'Barhat', 'Evening', 'N', 'slim_black-barhat', 'Dark', 'Y', 'https://presentandsimple.com/catalog/platya/plate-futlyar-adele-iz-barxata'),
('evening_dress_slim_black-barhat-odri', 'dress', 'Long', 'Barhat', 'Evening', 'N', 'slim_black-barhat-odri', 'Dark', 'Y', 'https://presentandsimple.com/catalog/platya/plate-odri-iz-barxata'),
('evening_dress_slim_black-lauren', 'dress', 'Long', 'Polyester', 'Evening', 'N', 'slim_black-lauren', 'Dark', 'Y', 'https://presentandsimple.com/catalog/platya/plate-lauren-113437'),
('evening_dress_slim_black-sexy', 'dress', 'Long', 'Silk', 'Evening', 'N', 'slim_black-sexy', 'Dark', 'Y', 'https://you-wanna.ru/catalog/platyaandsarafani/dress_dresses/product/880107010RSP25B/'),
('evening_dress_slim_black-silk', 'dress', 'Long', 'Silk', 'Evening', 'N', 'slim_black-silk', 'Dark', 'Y', 'https://presentandsimple.com/catalog/platya/plate-kombinaciya-boheme-113429'),
('evening_dress_slim_black-white', 'dress', 'Long', 'Polyester', 'Evening', 'N', 'slim_black-white', 'Dark', 'Y', 'https://studio-29.ru/catalog/trikotazh/113865/'),
('evening_dress_slim_black-with-mesh', 'dress', 'Long', 'Polyester', 'Evening', 'N', 'slim_black-with-mesh', 'Dark', 'Y', 'https://passywear.ru/tproduct/470231804-423862165281-plate-so-vstavkami-iz-setki'),
('evening_dress_slim_black-with-seams', 'dress', 'Long', 'Cotton', 'Classic', 'N', 'slim_black-with-seams', 'Dark', 'Y', 'https://xsai.store/women/tproduct/607434350-327026061061-long-dress-01'),
('evening_dress_slim_blue-silk', 'dress', 'Long', 'Silk', 'Evening', 'N', 'slim_blue-silk', 'Colourful', 'N', 'https://presentandsimple.com/catalog/platya/plate-emma-iz-selkovistoi-viskozy-113399'),
('evening_dress_slim_brown', 'dress', 'Long', 'Polyester', 'Casual', 'N', 'slim_brown', 'Dark', 'N', 'https://xsai.store/women/tproduct/607434350-612780131292-longsleeve-dress'),
('evening_dress_slim_brown-sexy', 'dress', 'Long', 'Silk', 'Evening', 'N', 'slim_brown-sexy', 'Dark', 'Y', 'https://you-wanna.ru/catalog/platyaandsarafani/dress_dresses/product/880107010RSP25/'),
('evening_dress_slim_brown-with-seams', 'dress', 'Long', 'Cotton', 'Classic', 'N', 'slim_brown-with-seams', 'Dark', 'Y', 'https://xsai.store/women/tproduct/607434350-916183966512-long-dress-01'),
('evening_dress_slim_grey', 'dress', 'Long', 'Cotton', 'Casual', 'N', 'slim_grey', 'Colourful', 'Y', 'https://toptop.ru/catalog/clothes/dresses/midi-dresses/2008723120904'),
('evening_dress_slim_grey-with-seams', 'dress', 'Long', 'Cotton', 'Classic', 'N', 'slim_grey-with-seams', 'Colourful', 'Y', 'https://xsai.store/women/tproduct/607434350-696134676911-long-dress-01'),
('evening_dress_slim_red', 'dress', 'Long', 'Polyester', 'Casual', 'N', 'slim_red', 'Colourful', 'N', 'https://xsai.store/women/tproduct/607434350-260600415862-longsleeve-dress'),
('evening_dress_slim_red-barhat', 'dress', 'Regular', 'Barhat', 'Evening', 'N', 'slim_red-barhat', 'Dark', 'Y', 'https://presentandsimple.com/catalog/platya/plate-futlyar-adele-iz-barxata-113454'),
('evening_dress_slim_red-with-seams', 'dress', 'Long', 'Cotton', 'Evening', 'N', 'slim_red-with-seams', 'Colourful', 'Y', 'https://xsai.store/women/tproduct/607434350-443866885651-long-dress-01'),
('evening_dress_slim_sand', 'dress', 'Long', 'Polyester', 'Casual', 'N', 'slim_sand', 'Light', 'N', 'https://xsai.store/women/tproduct/607434350-854845536492-longsleeve-dress'),
('evening_dress_slim_white', 'dress', 'Long', 'Polyester', 'Casual', 'N', 'slim_white', 'Light', 'N', 'https://xsai.store/women/tproduct/607434350-360920886712-longsleeve-dress'),
('evening_dress_slim_white-silk', 'dress', 'Long', 'Silk', 'Evening', 'N', 'slim_white-silk', 'Light', 'Y', 'https://presentandsimple.com/catalog/platya/plate-kombinaciya-boheme'),
('evening_dress_slim_white-with-seams', 'dress', 'Long', 'Cotton', 'Classic', 'N', 'slim_white-with-seams', 'Light', 'N', 'https://xsai.store/women/tproduct/607434350-746128987022-long-dress-01'),
('evening_skirt_balloon_black', 'skirt', 'Short', 'Polyester', 'Classic/evening', 'N', 'balloon_black', 'Dark', 'Y', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770101610RSP24/'),
('evening_skirt_balloon_blue-leopard', 'skirt', 'Short', 'Polyester', 'Evening', 'Y', 'balloon_blue-leopard', 'Colourful', 'Y', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770103310RS24/'),
('evening_skirt_balloon_white', 'skirt', 'Short', 'Polyester', 'Classic/evening', 'N', 'balloon_white', 'Light', 'Y', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770101610RSP24/'),
('evening_skirt_mini_black', 'skirt', 'Short', 'Polyester', 'Classic', 'N', 'mini_black', 'Dark', 'N', 'https://www.lamoda.ru/p/mp002xw0ihqy/clothes-loverepublic-yubka/?promotion_provider_id=8c3265bd-0be8-46ce-9991-adb47d5a55dc'),
('evening_skirt_mini_black-plaid', 'skirt', 'Short', 'Polyester', 'Classic', 'Y', 'mini_black-plaid', 'Dark', 'N', 'https://rosi-store.ru/catalog/clothes-skirts-shorts/yubka-iz-kostyumnoy-shersti/'),
('evening_skirt_mini_brown-plaid', 'skirt', 'Short', 'Polyester', 'Classic', 'Y', 'mini_brown-plaid', 'Colourful', 'N', 'https://rosi-store.ru/catalog/clothes-skirts-shorts/yubka-iz-kostyumnoy-shersti_4289/'),
('evening_skirt_mini_grey', 'skirt', 'Short', 'Polyester', 'Classic', 'N', 'mini_grey', 'Colourful', 'Y', 'https://toptop.ru/catalog/clothes/skirts/mini-skirts/2008723116402'),
('evening_skirt_straight_black-jeans', 'skirt', 'Long', 'Jeans', 'Evening', 'N', 'straight_black-jeans', 'Dark', 'Y', 'https://you-wanna.ru/catalog/jeans/jeansskirts/product/770400310TF24/'),
('evening_skirt_straight_black-silk', 'skirt', 'Long', 'Silk', 'Classic/evening', 'N', 'straight_black-silk', 'Dark', 'N', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770103710RF24/'),
('evening_skirt_straight_black-with-leather', 'skirt', 'Long', 'Leather', 'Classic/evening', 'N', 'straight_black-with-leather', 'Dark', 'Y', 'https://passywear.ru/tproduct/470231804-660082197861-yubka-kombinirovannaya'),
('evening_skirt_straight_black-with-ruffles', 'skirt', 'Regular', 'Leather', 'Evening', 'N', 'straight_black-with-ruffles', 'Dark', 'Y', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770200010LSP24/'),
('evening_skirt_straight_black-with-zipper', 'skirt', 'Regular', 'Polyester', 'Classic', 'N', 'straight_black-with-zipper', 'Dark', 'Y', 'https://passywear.ru/tproduct/470231804-825871495161-yubka-s-molniyami'),
('evening_skirt_straight_brown-silk', 'skirt', 'Long', 'Silk', 'Classic/evening', 'N', 'straight_brown-silk', 'Colourful', 'N', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770103710RF24SC/'),
('evening_skirt_straight_brown-vintage', 'skirt', 'Long', 'Polyester', 'Evening', 'Y', 'straight_brown-vintage', 'Dark', 'Y', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770200410RF24/'),
('evening_skirt_straight_brown-with-lines', 'skirt', 'Long', 'Polyester', 'Classic', 'Y', 'straight_brown-with-lines', 'Colourful', 'N', 'https://rosi-store.ru/catalog/clothes-skirts-shorts/yubka-maksi-v-polosku/'),
('evening_skirt_straight_grey', 'skirt', 'Long', 'Polyester', 'Classic', 'N', 'straight_grey', 'Light', 'N', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770103610RF24/'),
('evening_skirt_straight_grey-with-rhinestones', 'skirt', 'Long', 'Polyester', 'Classic', 'Y', 'straight_grey-with-rhinestones', 'Light', 'N', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770102710LF24/'),
('evening_skirt_straight_jeans', 'skirt', 'Regular', 'Jeans', 'Casual', 'N', 'straight_jeans', 'Light', 'Y', 'https://you-wanna.ru/catalog/jeans/jeansskirts/product/D251123/'),
('evening_skirt_straight_light-jeans', 'skirt', 'Regular', 'Jeans', 'Casual', 'N', 'straight_light-jeans', 'Light', 'Y', 'https://you-wanna.ru/catalog/jeans/jeansskirts/product/D251123/'),
('evening_skirt_straight_olive-silk', 'skirt', 'Long', 'Silk', 'Classic/evening', 'N', 'straight_olive-silk', 'Colourful', 'N', 'https://you-wanna.ru/catalog/pants_and_skirts/skirts/product/770103710RF24SC/'),
('evening_skirt_straight_sand', 'skirt', 'Long', 'Polyester', 'Classic', 'N', 'straight_sand', 'Colourful', 'N', 'https://toptop.ru/catalog/clothes/skirts/maxi-skirts/2008723120485'),
('evening_skirt_straight_white', 'skirt', 'Long', 'Silk', 'Classic/evening', 'N', 'straight_white', 'Light', 'N', 'https://presentandsimple.com/catalog/yubki/yubka-muse-iz-plotnoi-viskozy-115223'),
('lower_jeans_high-waist_baggy_dark-grey', 'jeans', 'Long', 'Jeans', 'Casual', 'N', 'high-waist_baggy_dark-grey', 'Dark', 'N', 'nan'),
('lower_jeans_high-waist _mom_dark-blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist _mom_dark-blue', 'Dark', 'N', 'https://yollo.com/women/jeans/djinsy-mom-s-effektom-potertosti/'),
('lower_jeans_high-waist _mom_light-blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist _mom_light-blue', 'Light', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/20491_3105_732-kislotno_sinii'),
('lower_jeans_high-waist _mom_light-grey', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist _mom_light-grey', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/20491_3105_732-arkticeskii_seryi'),
('lower_jeans_high-waist _mom_white', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist _mom_white', 'Light', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/12781_3105_166-molocnyi'),
('lower_jeans_high-waist_streight_blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist_streight_blue', 'Light', 'N', 'https://www.2moodstore.com/collection/odezhda/dzhinsy_wide_leg_wl100_tsveta_arktik/'),
('lower_jeans_high-waist_straight_dark-blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist_straight_dark-blue', 'Dark', 'N', 'https://toptop.ru/catalog/clothes/jeans/slouchy/2008723122663'),
('lower_jeans_high-waist_streight_light-blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist_streight_light-blue', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/12607_1547_073-sostarennyi_sinii'),
('lower_jeans_high-waist_streight_light-grey', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist_streight_light-grey', 'Light', 'N', 'https://www.2moodstore.com/collection/odezhda/dzhinsy_wide_leg_wl100_svetlo_serogo_tsveta_3/'),
('lower_jeans_high-waist_streight_vintage', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist_streight_vintage', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/16637_7073_032-vintaznyi_sinii'),
('lower_jeans_high-waist_streight_vintage-black', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist_streight_vintage-black', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/20372_7073_892-vyvarennyi_cernyi'),
('lower_jeans_high-waist_streight_white', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'high-waist_streight_white', 'Light', 'N', 'https://www.2moodstore.com/collection/odezhda/dzhinsy_wide_leg_wl100_molochnogo_tsveta/'),
('lower_jeans_high-waist_straight_worn-out', 'jeans', 'Long', 'Jeans', 'Casual', 'N', 'high-waist_straight_worn-out', 'Dark', 'Y', 'https://yollo.com/women/jeans/djinsy-shirokie-s-effektom-potertosti-2/'),
('lower_jeans_low-waist_baggy_black', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'low-waist_baggy_black', 'Dark', 'N', 'https://www.2moodstore.com/collection/katalog/dzhinsy_baggy_fit_bg301__s_metallizirovannym_pokrytiem/'),
('lower_jeans_low-waist_baggy_blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'low-waist_baggy_blue', 'Light', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/21943_9597_732-sinii_denim'),
('lower_jeans_low-waist_baggy_grey', 'jeans', 'Long', 'Jeans', 'Casual', 'N', 'low-waist_baggy_grey', 'Dark', 'Y', 'https://www.2moodstore.com/collection/katalog/dzhinsy_baggy_fit_bg305_serogo_tsveta_1/'),
('lower_jeans_low-waist_skinny-black', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'low-waist_skinny-black', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/20549_8362_440-temno_cernyi'),
('lower_jeans_low-waist_skinny-blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'low-waist_skinny-blue', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/20550_8362_400-vintaznyi_sinii'),
('lower_jeans_low-waist_streight_blue-Photoroom', 'jeans', 'Long', 'Jeans', 'Casual', 'N', 'low-waist_streight_blue-Photoroom', 'Colourful', 'Y', 'nan'),
('lower_jeans_low-waist_streight_dark-blue-Photoroom', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'low-waist_streight_dark-blue-Photoroom', 'Dark', 'N', 'nan'),
('lower_jeans_low-waist_streight_light-blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'low-waist_streight_light-blue', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/16840_3767_893-goluboi'),
('lower_jeans_regular-waist_baggy_light-blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'regular-waist_baggy_light-blue', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/18842_6327_893-nebesno_goluboi'),
('lower_jeans_regular-waist_straight_black', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'regular-waist_straight_black', 'Dark', 'N', 'https://yollo.com/women/jeans/djinsy-shirokie-so-sredney-posadkoy/'),
('lower_jeans_regular-waist_streight_blue', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'regular-waist_streight_blue', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/19476_3766_445-vintaznyi_sinii'),
('lower_jeans_regular-waist_streight_dark-black', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'regular-waist_streight_dark-black', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/19480_8363_441-sinii_denim'),
('lower_jeans_regular-waist_streight_light-grey', 'jeans', 'Long', 'Jeans', 'Classic/casual', 'N', 'regular-waist_streight_light-grey', 'Light', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/19415_8404_892-arkticeskii_seryi'),
('lower_pants_black', 'pants', 'Long', 'Polyester', 'Classic', 'N', 'black', 'Dark', 'N', 'https://you-wanna.ru/catalog/pants_and_skirts/pants/product/440103310RSP25/'),
('lower_pants_black-polyester', 'pants', 'Long', 'Leather', 'Classic/evening', 'N', 'black-leather', 'Dark', 'N', 'https://studio-29.ru/catalog/bryuki_shorty/115727/'),
('lower_pants_black', 'pants', 'Long', 'Polyester', 'Classic', 'N', 'black-wide', 'Dark', 'N', 'nan'),
('lower_pants_black', 'pants', 'Long', 'Polyester', 'Classic', 'N', 'black-wide', 'Dark', 'Y', 'https://you-wanna.ru/catalog/pants_and_skirts/pants/product/Predzakaz12119950/'),
('lower_pants_beige-leather', 'pants', 'Long', 'Leather', 'Classic/evening', 'N', 'bordo-leather', 'Dark', 'N', 'https://studio-29.ru/catalog/bryuki_shorty/115732/'),
('lower_pants_brown', 'pants', 'Long', 'Polyester', 'Classic', 'N', 'black-wide', 'Dark', 'N', 'https://yollo.com/women/trousers/bruki-iz-kostumnoy-tkani-s-otvorotom/?color=796'),
('lower_pants_brown', 'pants', 'Long', 'Polyester', 'Classic', 'N', 'brown-bananas', 'Dark', 'N', 'https://www.2moodstore.com/collection/odezhda/bryuki_banany_bezhevogo_tsveta/'),
('lower_pants_beige-leather', 'pants', 'Long', 'Polyester', 'Classic/casual', 'Y', 'grey-wide-with-strips', 'Dark', 'N', 'https://you-wanna.ru/catalog/pants_and_skirts/pants/product/440102910RW24/'),
('lower_pants_bordo', 'pants', 'Long', 'Polyester', 'Classic/evening', 'N', 'red', 'Colourful', 'N', 'https://yollo.com/women/trousers/bruki-iz-kostumnoy-tkani-3/?color=798'),
('lower_pants_aubergine', 'pants', 'Long', 'Polyester', 'Classic/evening', 'N', 'white-high-rise', 'Light', 'N', 'https://you-wanna.ru/catalog/pants_and_skirts/pants/product/440102810RW24/'),
('lower_sporty-pants_sweatpants_beige', 'sporty-pants', 'Long', 'Cotton', 'Casual', 'N', 'sweatpants_beige', 'Light', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/20244_8094_401-kamennyi'),
('lower_sporty-pants_sweatpants_black', 'sporty-pants', 'Long', 'Cotton', 'Casual', 'N', 'sweatpants_black', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/22851_4420_010-cernyi'),
('lower_sporty-pants_sweatpants_brown', 'sporty-pants', 'Long', 'Cotton', 'Casual', 'N', 'sweatpants_black', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/20244_8094_401-temno_koricnevyi'),
('lower_sporty-pants_sweatpants_grey', 'sporty-pants', 'Long', 'Cotton', 'Casual', 'N', 'sweatpants_black', 'Dark', 'N', 'Ссылка на продукт: https://lime-shop.com/ru_ru/product/20244_8094_401-temno_seryi'),
('set_classic_black', 'classic', 'Regular', 'Akril', 'Classic', 'N', 'black', 'Dark', 'N', 'https://studio-29.ru/catalog/trikotazh/115882/https://studio-29.ru/catalog/yubki/115928/'),
('set_classic_blue', 'classic', 'Short', 'Akril', 'Classic/evening', 'N', 'blue', 'Light', 'Y', 'https://studio-29.ru/catalog/pidzhaki_zhakety/113092/https://studio-29.ru/catalog/yubki/113090/'),
('set_classic_brown', 'classic', 'Regular', 'Akril', 'Classic', 'N', 'brown', 'Dark', 'N', 'https://studio-29.ru/catalog/trikotazh/115807/https://studio-29.ru/catalog/yubki/115805/'),
('set_classic_grey', 'classic', 'Regular', 'Akril', 'Classic', 'N', 'grey', 'Colourful', 'Y', 'https://studio-29.ru/catalog/yubki/117427/https://studio-29.ru/catalog/trikotazh/117429/'),
('set_classic_white', 'classic', 'Regular', 'Akril', 'Classic', 'N', 'white', 'Light', 'Y', 'https://studio-29.ru/catalog/yubki/117428/https://studio-29.ru/catalog/trikotazh/117431/'),
('set_knitted-suit_brown', 'knitted-suit', 'Long', 'Cotton', 'Casual', 'N', 'brown', 'Colourful', 'N', 'nan'),
('set_knitted-suit_grey', 'knitted-suit', 'Long', 'Cotton', 'Casual', 'N', 'grey', 'Light', 'N', 'https://studio-29.ru/catalog/yubki/116073/https://studio-29.ru/catalog/trikotazh/116074/'),
('set_tracksuit_brown', 'tracksuit', 'Long', 'Cotton', 'Casual', 'N', 'brown', 'Dark', 'Y', 'nan'),
('set_tracksuit_graffit', 'tracksuit', 'Long', 'Cotton', 'Casual', 'N', 'graffit', 'Dark', 'N', 'https://presentandsimple.com/catalog/bryuki/bryuki-country-club-iz-100-xlopkahttps://presentandsimple.com/catalog/svitsoty-i-xudi/svitsot-country-club-iz-100-xlopka'),
('set_tracksuit_grey', 'tracksuit', 'Long', 'Cotton', 'Casual', 'N', 'grey', 'Light', 'Y', 'nan'),
('set_tracksuit_milk', 'tracksuit', 'Long', 'Cotton', 'Casual', 'N', 'milk', 'Light', 'N', 'https://studio-29.ru/catalog/bryuki_shorty/116038/https://studio-29.ru/catalog/trikotazh/116041/'),
('set_tracksuit_white', 'tracksuit', 'Long', 'Cotton', 'Casual', 'N', 'white', 'Light', 'N', 'nan'),
('winter-top_coat_beige', 'coat', 'Long', 'Polyester', 'Classic', 'N', 'beige', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/17366_3708_869-sero_bezevyi'),
('winter-top_coat_beige-cropped', 'coat', 'Short', 'Polyester', 'Casual', 'N', 'beige-cropped', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/20780_7592_115-svetlo_bezevyi_melanz'),
('winter-top_coat_beige-quilted-with-belt', 'coat', 'Long', 'nan', 'nan', 'nan', 'beige-quilted-with-belt', 'nan', 'nan', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/zhenskoe-palto/264803/'),
('winter-top_coat_black', 'coat', 'Long', 'Polyester', 'Classic/casual', 'N', 'black', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/23769_7368_795-cernyi'),
('winter-top_coat_black-down', 'coat', 'Long', 'Polyester', 'Casual', 'N', 'black-down', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/21677_9904_591-cernyi'),
('winter-top_coat_black-quilted-with-belt', 'coat', 'Long', 'Polyester', 'Casual', 'N', 'black-down', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/zhenskoe-palto/264808/'),
('winter-top_coat_brown-down', 'coat', 'Long', 'Polyester', 'Casual', 'N', 'brown-down', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/21513_8664_522-koricnevyi_melanz'),
('winter-top_coat_brown-oversize', 'coat', 'Long', 'Polyester', 'Classic/casual', 'N', 'brown-oversize', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/23767_3414_039-sero_koricnevyi_melanz'),
('winter-top_coat_grey-with-belt', 'coat', 'Long', 'Polyester', 'Classic/casual', 'N', 'grey-with-belt', 'Dark', 'N', 'https://rosi-store.ru/catalog/palto-i-trenchi/palto-gentle-iz-myagkogo-vorsa_4576/'),
('winter-top_coat_khaki-cropped', 'coat', 'Regular', 'Polyester', 'Classic/casual', 'N', 'khaki-cropped', 'Colourful', 'N', 'https://lichi.com/ru/ru/product/45921'),
('winter-top_coat_white', 'coat', 'Long', 'Polyester', 'Classic/casual', 'N', 'white', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/20406_9367_421-kremovyi'),
('winter-top_coat_white-with-belt', 'coat', 'Long', 'Polyester', 'Classic/casual', 'N', 'white-with-belt', 'Light', 'N', 'https://lichi.com/ru/ru/product/44436'),
('winter-top_fur-coat_beige-cropped', 'fur-coat', 'Short', 'Fur', 'Classic/evening', 'N', 'beige-cropped', 'Light', 'N', 'https://lookonline.ru/product/polupalto-ukorocennoe-iz-iskustvennogo-mexa-molocnyi'),
('winter-top_fur-coat_black', 'fur-coat', 'Long', 'Fur', 'Classic/evening', 'N', 'black', 'Dark', 'N', 'https://yollo.com/women/furs/shuba-iz-ekomeha-s-poyasom/'),
('winter-top_fur-coat_black-cropped', 'fur-coat', 'Short', 'Fur', 'Classic/evening', 'N', 'black-cropped', 'Dark', 'N', 'https://lichi.com/ru/ru/product/48128'),
('winter-top_fur-coat_brown', 'fur-coat', 'Long', 'Fur', 'Classic/evening', 'N', 'brown', 'Colourful', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/zhenskoe-palto/264486/'),
('winter-top_fur-coat_brown-cropped', 'fur-coat', 'Short', 'Fur', 'Classic/evening', 'N', 'brown-cropped', 'Colourful', 'N', 'https://lookonline.ru/product/suba-ukorocennaia-iz-ekomexa-koricnevyi'),
('winter-top_fur-coat-dark-brown', 'fur-coat-dark-brown', 'Long', 'Fur', 'Classic/evening', 'N', 'nan', 'Dark', 'N', 'https://lime-shop.com/ru_ru/product/21067_8046_483-temno_koricnevyi'),
('winter-top_fur-coat_dark-grey-cropped', 'fur-coat', 'Short', 'Fur', 'Classic/evening', 'N', 'dark-grey-cropped', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/zhenskoe-palto/264681/'),
('winter-top_fur-coat_white', 'fur-coat', 'Long', 'Fur', 'Classic/evening', 'N', 'white', 'Light', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/zhenskoe-palto/266232/'),
('winter-top_fur-coat_white-cropped', 'fur-coat', 'Short', 'Fur', 'Classic/evening', 'N', 'white-cropped', 'Light', 'N', 'https://lichi.com/ru/ru/product/48130'),
('winter-top_parka_beige', 'parka', 'Regular', 'Polyester', 'Casual', 'N', 'beige', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/21697_8667_523-kamennyi'),
('winter-top_parka_black', 'parka', 'Regular', 'Polyester', 'Casual', 'N', 'black', 'Dark', 'N', 'https://toptop.ru/catalog/clothes/outerwear/parkas/2008723128665'),
('winter-top_parka_brown', 'parka', 'Regular', 'Polyester', 'Casual', 'N', 'black', 'Dark', 'N', 'https://toptop.ru/catalog/clothes/outerwear/parkas/2008723133126'),
('winter-top_parka_brown-leather', 'parka', 'Regular', 'Leather', 'Casual', 'N', 'brown-leather', 'Dark', 'N', 'https://toptop.ru/catalog/clothes/outerwear/parkas/2008723129136'),
('winter-top_parka_khaki', 'parka', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Colourful', 'N', 'https://rosi-store.ru/catalog/kurtki-i-pukhoviki/parka-na-poyase-s-kapyushonom_6944/'),
('winter-top_parka_white', 'parka', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Light', 'N', 'https://toptop.ru/catalog/clothes/outerwear/winter-jackets/2008723119724'),
('winter-top_puffer-jacket_oversize_beige', 'puffer-jacket', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Light', 'N', 'https://lime-shop.com/ru_ru/product/21186_9909_582-kamennyi'),
('winter-top_puffer-jacket_oversize_beige-cropped', 'puffer-jacket', 'Short', 'Polyester', 'Casual', 'N', 'khaki', 'Light', 'N', 'C:\Users\zayts\AppData\Local\Temp\4c82067c-cfc3-4813-a48c-e247c74f698f_winter-top%202.zip.98f\winter-top\puffer-jacket\oversize\light\winter-top_puffer-jacket_oversize_light.html'),
('winter-top_puffer-jacket_oversize_black', 'puffer-jacket', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/263425/'),
('winter-top_puffer-jacket_oversize_black-bomber', 'puffer-jacket', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/274455/'),
('winter-top_puffer-jacket_oversize_black-cropped', 'puffer-jacket', 'Short', 'Polyester', 'Casual', 'N', 'khaki', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/266202/'),
('winter-top_puffer-jacket_oversize_brown-cropped', 'puffer-jacket', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/264279/'),
('winter-top_puffer-jacket_oversize_burgundy', 'puffer-jacket', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Colourful', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/266270/'),
('winter-top_puffer-jacket_oversize_dark-blue', 'puffer-jacket', 'Short', 'Vilvet', 'Casual', 'N', 'khaki', 'Dark', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/265916/'),
('winter-top_puffer-jacket_oversize_grey', 'puffer-jacket', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Light', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/263426/'),
('winter-top_puffer-jacket_oversize_khaki-cropped', 'puffer-jacket', 'Short', 'Polyester', 'Casual', 'N', 'khaki', 'Colourful', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/266197/'),
('winter-top_puffer-jacket_oversize_khaki-quilted', 'puffer-jacket', 'Regular', 'Polyester', 'Casual', 'N', 'khaki', 'Colourful', 'N', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/274455/'),
('winter-top_sheepskin-coat_beige-cropped', 'sheepskin-coat', 'Short', 'Sheep', 'Casual', 'N', 'beige-cropped', 'Light', 'Y', 'https://lookonline.ru/product/dublenka-oversize-s-remniami-belyi'),
('winter-top_sheepskin-coat_black', 'sheepskin-coat', 'Regular', 'Sheep', 'Casual', 'N', 'black', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/263300/'),
('winter-top_sheepskin-coat_black-long', 'sheepskin-coat', 'Long', 'Sheep', 'Classic/casual', 'N', 'black-long', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/265855/'),
('winter-top_sheepskin-coat_blue', 'sheepskin-coat', 'Short', 'Sheep', 'Casual', 'N', 'blue', 'Light', 'Y', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/kurtki/270176/'),
('winter-top_sheepskin-coat_brown-cropped', 'sheepskin-coat', 'Short', 'Sheep', 'Casual', 'N', 'brown-cropped', 'Dark', 'Y', 'https://yollo.com/women/furs/dublenka-ukorochennaya-s-ekomehom/'),
('winter-top_sheepskin-coat_brown-long', 'sheepskin-coat', 'Long', 'Sheep', 'Classic/casual', 'N', 'brown-long', 'Dark', 'Y', 'https://loverepublic.ru/catalog/odezhda/verhnyaya-odezhda/265856/');

-- Шаг 5: Проверяем результат
SELECT COUNT(*) as total_items FROM wardrobe_items;
SELECT * FROM wardrobe_items LIMIT 5;
SELECT item_type, COUNT(*) as count FROM wardrobe_items GROUP BY item_type ORDER BY count DESC;
